export const songs = [
  {
    artist: "CAKE",
    name: "The Distance",
    youtubeId: "JH6il8U3EU0"
  },
  { artist: "Avril Lavigne", name: "Girlfriend", youtubeId: "g0TiuFwX0r8" },
  { artist: "Anders Nilsen", name: "Salsa Tequila", youtubeId: "CgZDGe_5xS4" },
  { artist: "Linkin Park", name: "Bleed It Out", youtubeId: "bSwzZoLCoZ0" },
  { artist: "Def Leppard", name: "Animal", youtubeId: "1mgpMqQKEh8" },
  { artist: "Green Day", name: "When I Come Around", youtubeId: "06HcqK2vvlw" },
  { artist: "Phil Collins", name: "I Don't Care Anymore", youtubeId: "C6PNc9KN50M" },
  { artist: "Bag Raiders", name: "Shooting Stars", youtubeId: "O-MQC_G9jTU" },
  { artist: "Lifehouse", name: "Hanging By A Moment", youtubeId: "NPgN0j6fm0w" },
  { artist: "Toby Fox", name: "Undertale (Undertale)", youtubeId: "8CeYNJ-s0Kw" },
  { artist: "Spice Girls", name: "Wannabe", youtubeId: "tscL_I2v7pU" },
  { artist: "AC/DC", name: "Back In Black", youtubeId: "pAgnJDJN4VA" },
  { artist: "Metallica", name: "For Whom The Bell Tolls", youtubeId: "B_HSa1dEL9s" },
  { artist: "Fun.", name: "Some Nights", youtubeId: "O8g_iLP_9go" },
  { artist: "Snoop Dogg, Pharrell Williams", name: "Drop It Like It's Hot", youtubeId: "ldjajgAHAu4" },
  { artist: "Kendrick Lamar, MC Eiht", name: "m.A.A.d city", youtubeId: "AuikIJZpt_8" },
  { artist: "The Police", name: "Every Breath You Take", youtubeId: "-SaUrDhp034" },
  { artist: "Bon Jovi", name: "Runaway", youtubeId: "kb2DgAF3egQ" },
  { artist: "Judas Priest", name: "You've Got Another Thing Coming", youtubeId: "LNyIhirtXUI" },
  { artist: "Gorillaz", name: "Feel Good Inc.", youtubeId: "NxxjLD2pmlk" },
  { artist: "R.E.M.", name: "Man On The Moon", youtubeId: "CO5GaVJiRwo" },
  { artist: "Sunstroke Project, Olia Tira", name: "Run Away", youtubeId: "TMku5KCNkb4" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Overture (Halo: Reach)", youtubeId: "3A7WIn06ceA" },
  { artist: "Harry Belafonte", name: "Day O (Banana Boat Song)", youtubeId: "YO7M0Hx_1D8" },
  { artist: "Ted Nugent", name: "Stranglehold", youtubeId: "MRj5KT3742o" },
  { artist: "Electric Light Orchestra", name: "Is It Alright", youtubeId: "zbiTRjCuGi0" },
  { artist: "Bee Gees", name: "Stayin' Alive", youtubeId: "W_dDNNEdIJg" },
  { artist: "_ensnare_", name: "I Drop Gems", youtubeId: "4dqsl-bbqVU" },
  { artist: "R.E.M.", name: "It's The End Of The World As We Know It (And I Feel Fine)", youtubeId: "-s97_bBGobQ" },
  { artist: "Ben Prunty", name: "MilkyWay (Explore) (FTL: Faster than Light)", youtubeId: "lwJ8L0QL_qY" },
  { artist: "The Tubes", name: "She's A Beauty", youtubeId: "k6YzNrA6Elk" },
  { artist: "Jack Stauber's Micropop", name: "Inchman", youtubeId: "6AHrEjteu-E" },
  { artist: "Warren Zevon", name: "Werewolves of London", youtubeId: "lh0w01S7Jnk" },
  { artist: "Toby Fox", name: "MEGALOVANIA (Undertale)", youtubeId: "0FCvzsVlXpQ" },
  { artist: "KT Tunstall", name: "Black Horse And The Cherry Tree", youtubeId: "qWKcNoerynI" },
  { artist: "Kenny Loggins", name: "Footloose (From \"Footloose\" Soundtrack)", youtubeId: "HvropLxYb5c" },
  { artist: "A Flock Of Seagulls", name: "I Ran (So Far Away) (Single Edit)", youtubeId: "cEgMousgsqQ" },
  { artist: "Mat Zo", name: "Defined", youtubeId: "DZF46bDWljQ" },
  { artist: "The Hives", name: "Tick Tick Boom", youtubeId: "NwVwsW0XZvY" },
  { artist: "Home", name: "We're Finally Landing", youtubeId: "M-0TB9JMpdE" },
  { artist: "Aerosmith", name: "Rag Doll", youtubeId: "Xp9WFBsi3NE" },
  { artist: "Selena Gomez", name: "Come & Get It", youtubeId: "APXB7op_aRQ" },
  { artist: "Linda Ronstadt", name: "Blue Bayou", youtubeId: "IDBVW4BXZPo" },
  { artist: "Third Eye Blind", name: "How's It Going to Be", youtubeId: "2dITTT-OaWE" },
  { artist: "Soft Cell", name: "Tainted Love / Where Did Our Love Go (Extended Version / Medley)", youtubeId: "q84psZX6MbA" },
  { artist: "Empire of the Sun", name: "Wandering Star (Dumb and Dumber To)", youtubeId: "KvuCinEJJHw" },
  { artist: "Eiffel 65", name: "Blue (Da Ba Dee) (Video Edit)", youtubeId: "kyzIQKuSqBs" },
  { artist: "Eric Prydz", name: "Pjanoo (Radio Edit)", youtubeId: "zVtEBow2E7g" },
  { artist: "U2", name: "Beautiful Day", youtubeId: "V1j_MA3daLI" },
  { artist: "Daft Punk", name: "Harder, Better, Faster, Stronger", youtubeId: "JhulBGMA7G4" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Delta Halo Suite (Halo 2)", youtubeId: "dvuyErXPLdo" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Halo (Halo: Combat Evolved)", youtubeId: "Bzrnw4niuTA" },
  { artist: "The Weather Girls", name: "It's Raining Men", youtubeId: "4x6leDGV7gs" },
  { artist: "Styx", name: "Fooling Yourself (The Angry Young Man)", youtubeId: "apTy_Wez4V4" },
  { artist: "Dire Straits", name: "Sultans of Swing", youtubeId: "xZatdZ_bqOc" },
  { artist: "Justice", name: "D.A.N.C.E.", youtubeId: "tCnBrrnOefs" },
  { artist: "Katy Perry", name: "Roar", youtubeId: "6nJuUdc2qNg" },
  { artist: "King Harvest, Sherman Kelly", name: "Dancing in the Moonlight", youtubeId: "0eHBLHVHjWg" },
  { artist: "Ted Poley, Tony Harnell, Jun Senoue", name: "Escape From The City ... for City Escape (Sonic Adventure 2)", youtubeId: "qR6mTJRbcaE" },
  { artist: "Madonna", name: "Like a Prayer", youtubeId: "IaHQYTm14Kc" },
  { artist: "Pegboard Nerds", name: "Disconnected", youtubeId: "5gUYr7LYKkw" },
  { artist: "Toad The Wet Sprocket", name: "Rock And Roll All Nite", youtubeId: "HlDyCgS8E3w" },
  { artist: "NOMA", name: "Brain Power (Long Version)", youtubeId: "cVP8D_FwPU8" },
  { artist: "Yes", name: "Roundabout (2008 Remaster)", youtubeId: "cPCLFtxpadE" },
  { artist: "Pitbull, TJR", name: "Don't Stop the Party", youtubeId: "52vzL3sFUT0" },
  { artist: "Eve 6", name: "Inside Out", youtubeId: "WkcQt-1j-SE" },
  { artist: "Blackstreet, Dr. Dre, Queen Pen", name: "No Diggity", youtubeId: "Fiu9h8ZTPoQ" },
  { artist: "Michael Jackson", name: "P.Y.T. (Pretty Young Thing)", youtubeId: "y32ejtuxSjM" },
  { artist: "Duran Duran", name: "Is There Something I Should Know?", youtubeId: "zUk-XaYDwIU" },
  { artist: "Oingo Boingo", name: "Dead Man's Party", youtubeId: "9cF8XQPQ1lU" },
  { artist: "Bananarama", name: "I Heard a Rumour", youtubeId: "4KI7twZHJdw" },
  { artist: "Pat Benatar", name: "Heartbreaker", youtubeId: "nsSx6nXpBMg" },
  { artist: "John Fogerty", name: "Centerfield", youtubeId: "LVTXn9Y3dM0" },
  { artist: "Loona", name: "Vamos a la Playa (Radio Edit)", youtubeId: "xmDc-1IrYRU" },
  { artist: "Electric Light Orchestra", name: "Showdown", youtubeId: "dV0-Cho26IY" },
  { artist: "Smash Mouth", name: "Walkin' On The Sun", youtubeId: "v-4pqHjpguE" },
  { artist: "Hechizeros Band", name: "El Sonidito", youtubeId: "iN3th1Gt_XY" },
  { artist: "Lynyrd Skynyrd", name: "Sweet Home Alabama", youtubeId: "iL-jC7XyLeo" },
  { artist: "deadmau5 ft Rob Swire", name: "Ghosts 'n' Stuff", youtubeId: "pb-EwykPTv8" },
  { artist: "The Animals", name: "House Of The Rising Sun", youtubeId: "s_Kecv6eJNM" },
  { artist: "Joan Jett & the Blackhearts", name: "I Love Rock 'N Roll", youtubeId: "d9jhDwxt22Y" },
  { artist: "Danny Elfman", name: "Breakfast Machine (From \"Pee Wee's Big Adventure\")", youtubeId: "KoLOtsm_Jow" },
  { artist: "Scatman John", name: "Scatman (ski-ba-bop-ba-dop-bop)", youtubeId: "Eht9W25tDZo" },
  { artist: "Howard Jones", name: "Things Can Only Get Better", youtubeId: "4XkdBMxPCkc" },
  { artist: "Orleans", name: "Still the One", youtubeId: "SdfW_2frXnE" },
  { artist: "The Babys", name: "Isn't It Time", youtubeId: "K52eWjgIBm0" },
  { artist: "Aerosmith", name: "Love In An Elevator", youtubeId: "EsUUr22n8N4" },
  { artist: "Marvin Gaye", name: "Too Busy Thinking About My Baby", youtubeId: "eyZgAbXfsL4" },
  { artist: "Rush", name: "Tom Sawyer", youtubeId: "QJ4-9tAf9UQ" },
  { artist: "3 Doors Down", name: "Kryptonite", youtubeId: "xPU8OAjjS4k" },
  { artist: "Seal", name: "Fly Like an Eagle", youtubeId: "QVvUbBHd7Zg" },
  { artist: "Pink Floyd", name: "Mother", youtubeId: "xe3NUKCnZp4" },
  { artist: "M.O.O.N", name: "Dust", youtubeId: "phL6fDiYNJk" },
  { artist: "Kiss", name: "Rock And Roll All Nite", youtubeId: "f-S3X2saSwM" },
  { artist: "Arcade Fire", name: "Everything Now", youtubeId: "6vG5WqYJViY" },
  { artist: "Fleetwood Mac", name: "Go Your Own Way (2004 Remaster)", youtubeId: "MTIkFwMuiTw" },
  { artist: "New Order", name: "Bizarre Love Triangle", youtubeId: "bKVbB_qZQcU" },
  { artist: "Marietta", name: "Destination Unknown (From \"Top Gun\" Original Soundtrack)", youtubeId: "XfYmlhz3mIk" },
  { artist: "Neon Trees", name: "Everybody Talks", youtubeId: "JwlHM8TvFE4" },
  { artist: "Bonnie Tyler", name: "Holding Out for a Hero (From \"Footloose\" Soundtrack)", youtubeId: "qgHVh5jspsA" },
  { artist: "Blind Melon", name: "No Rain", youtubeId: "mjN4dMvC0Gs" },
  { artist: "Mike Posner", name: "I Took A Pill In Ibiza (Seeb Remix)", youtubeId: "Ah0srVZq9ac" },
  { artist: "John Mellencamp", name: "Jack & Diane", youtubeId: "DEF52ShgEMU" },
  { artist: "Britney Spears", name: "Toxic", youtubeId: "tVdr_JWmnsA" },
  { artist: "The White Stripes", name: "Seven Nation Army", youtubeId: "D_QLxj8jCF0" },
  { artist: "Billy Squier", name: "Everybody Wants You", youtubeId: "q0aLYYn_6tM" },
  { artist: "Above & Beyond feat. Zoë Johnston", name: "Sahara Love", youtubeId: "DUFBQqhxR8c" },
  { artist: "Fleetwood Mac", name: "Landslide", youtubeId: "k4M53xndqiU" },
  { artist: "American Authors", name: "Best Day Of My Life", youtubeId: "BeOa6kRA6aw" },
  { artist: "Modest Mouse", name: "Dashboard", youtubeId: "21euaOPVneM" },
  { artist: "Kristofer Maddigan", name: "Clip Joint Calamity", youtubeId: "RRCiA55yZe0" },
  { artist: "The Verve", name: "Bitter Sweet Symphony", youtubeId: "JnRw8bXVbPI" },
  { artist: "twenty one pilots", name: "Car Radio", youtubeId: "Z_Jp2mlzEjw" },
  { artist: "Matchbox Twenty", name: "Unwell", youtubeId: "VTgMFcFIH9k" },
  { artist: "Robbie Williams", name: "It's Only Us", youtubeId: "0eRNOMcMUHQ" },
  { artist: "Creedence Clearwater Revival", name: "Fortunate Son", youtubeId: "r5NzAksjfDI" },
  { artist: "Boston", name: "Foreplay / Long Time", youtubeId: "QlMUlpju3qo" },
  { artist: "Gwen Stefani, Eve", name: "Rich Girl", youtubeId: "cem_uAOsouE" },
  { artist: "Bloc Party", name: "Helicopter", youtubeId: "deM4ueJpMbY" },
  { artist: "Queens Of The Stone Age", name: "3's & 7's", youtubeId: "HBo_R-MRazU" },
  { artist: "Hootie & The Blowfish", name: "Only Wanna Be with You", youtubeId: "62F4rAa-CK0" },
  { artist: "Carole King", name: "Sweet Seasons", youtubeId: "PUBO1G1c55U" },
  { artist: "Jimmy Buffett", name: "Cheeseburger In Paradise", youtubeId: "7PfZ4QVqCs8" },
  { artist: "John Mellencamp", name: "Hurts So Good", youtubeId: "NcdLoKlqlQU" },
  { artist: "Toby Fox", name: "Rude Buster (Deltarune)", youtubeId: "GPL5Hkl11IQ" },
  { artist: "Al Stewart", name: "Song on the Radio", youtubeId: "VaSx2k_dfSc" },
  { artist: "twenty one pilots", name: "Ode to Sleep", youtubeId: "Vp3WQ_iWh3c" },
  { artist: "Guns N' Roses", name: "Knockin' On Heaven's Door", youtubeId: "f8OHybVhQwc" },
  { artist: "Foo Fighters", name: "The Pretender", youtubeId: "BMMGwtklEeE" },
  { artist: "Alanis Morissette", name: "You Oughta Know", youtubeId: "pcYGTI_Bfv8" },
  { artist: "Ellis", name: "Orbit", youtubeId: "uHNkmXAe2js" },
  { artist: "M.O.O.N.", name: "'Hydrogen' [Hotline Miami Soundtrack]", youtubeId: "SNE2oCZH_4k" },
  { artist: "Hyper Potions", name: "Time Trials (Sonic Mania)", youtubeId: "BkfUUV5R8iA" },
  { artist: "Fountains Of Wayne", name: "Stacy's Mom", youtubeId: "sT_hnNDstnE" },
  { artist: "Crazy Frog", name: "Axel F", youtubeId: "_M1iPYsHZvU" },
  { artist: "David Guetta, Akon, Aliaune \"Akon\" Thiam", name: "Sexy Chick (feat. Akon)", youtubeId: "dZIYHbiCqfs" },
  { artist: "Miike Snow", name: "Paddling Out", youtubeId: "d7FHg0cw4RA" },
  { artist: "Europe", name: "The Final Countdown", youtubeId: "NNiTxUEnmKI" },
  { artist: "Alanis Morissette", name: "Ironic", youtubeId: "E1ILlhZPAoc" },
  { artist: "Bob Seger & The Silver Bullet Band", name: "Old Time Rock And Roll", youtubeId: "eMY1ewg-e9w" },
  { artist: "Electric Light Orchestra", name: "Turn to Stone", youtubeId: "7gncH7WOQvY" },
  { artist: "Lady Gaga", name: "Bad Romance", youtubeId: "fXgLARPprRc" },
  { artist: "No Doubt", name: "Don't Speak", youtubeId: "Q7uiJcxIsK4" },
  { artist: "Level 42", name: "Something About You", youtubeId: "WtKxEmuSxBc" },
  { artist: "Blackalicious", name: "Alphabet Aerobics", youtubeId: "zlynqOgBAUw" },
  { artist: "Katy Perry, Snoop Dogg", name: "California Gurls", youtubeId: "ru3tYeyIOFk" },
  { artist: "Elton John", name: "Crocodile Rock", youtubeId: "75r0nQu-hMs" },
  { artist: "SEGA, Takenobu Mitsuyoshi, Takenobu Mitsuyoshi", name: "Let's Go Away (Daytona USA)", youtubeId: "5ToNSY-yG_M" },
  { artist: "The Human League", name: "[Keep Feeling] Fascination", youtubeId: "CrnGQ2-bri4" },
  { artist: "Foreigner", name: "Hot Blooded (2008 Remaster)", youtubeId: "FusX37u4cNA" },
  { artist: "No Doubt", name: "It's My Life", youtubeId: "bpUgcEc3iLw" },
  { artist: "Rush", name: "The Spirit Of Radio", youtubeId: "wPBinohXHLc" },
  { artist: "Basshunter", name: "DotA (Radio Edit)", youtubeId: "TuNyDfHKzlk" },
  { artist: "Eminem", name: "My Name Is", youtubeId: "I_bBRzWzkC8" },
  { artist: "John Denver", name: "Take Me Home, Country Roads (Original Version)", youtubeId: "c0dvabcWVo0" },
  { artist: "The Doobie Brothers", name: "Black Water", youtubeId: "RsP3rFJJk1Y" },
  { artist: "Ides Of March", name: "Vehicle", youtubeId: "bq95nZBbNHI" },
  { artist: "Aerosmith", name: "I Don't Want to Miss a Thing", youtubeId: "JkK8g6FMEXE" },
  { artist: "Steve Miller Band", name: "Abracadabra", youtubeId: "dKCV8gzSlYw" },
  { artist: "Michael Jackson", name: "The Way You Make Me Feel (2012 Remaster)", youtubeId: "VtM-rHPwN7o" },
  { artist: "Guns N' Roses", name: "Welcome To The Jungle", youtubeId: "0CNPR2qNzxk" },
  { artist: "Styx", name: "Mr. Roboto", youtubeId: "3n_7acSpvuo" },
  { artist: "Approaching Nirvana", name: "305", youtubeId: "uEOavBkGV9k" },
  { artist: "Owl City", name: "Fireflies", youtubeId: "KWLGyeg74es" },
  { artist: "Red Hot Chili Peppers", name: "Under the Bridge", youtubeId: "4UnU3r0M3zg" },
  { artist: "England Dan & John Ford Coley", name: "I'd Really Love to See You Tonight", youtubeId: "P8RShs00yR0" },
  { artist: "Sweet", name: "Ballroom Blitz", youtubeId: "7Aze726qAwA" },
  { artist: "The O'Jays", name: "For the Love of Money", youtubeId: "7KlxInHeH5Q" },
  { artist: "Steve Miller Band", name: "Take The Money And Run", youtubeId: "ido6NrjGi2o" },
  { artist: "Glenn Frey", name: "The Heat Is On (From \"Beverly Hills Cop\" Soundtrack)", youtubeId: "uKWgYKa2Fh0" },
  { artist: "Bowling For Soup", name: "High School Never Ends", youtubeId: "xPub2CzBEVM" },
  { artist: "Matchbox Twenty", name: "Back 2 Good", youtubeId: "kBHnTyiquAA" },
  { artist: "Shania Twain", name: "Up! (Red Version)", youtubeId: "PH6mxRhp1ZQ" },
  { artist: "twenty one pilots", name: "Morph", youtubeId: "rYuBU7YzZ-c" },
  { artist: "Steve Miller Band", name: "Jet Airliner", youtubeId: "JHa1hiFYbFQ" },
  { artist: "Fatboy Slim", name: "The Rockafeller Skank", youtubeId: "wD6jCMn5nq0" },
  { artist: "Gwen Stefani", name: "Hollaback Girl", youtubeId: "7YQESUr8Cxc" },
  { artist: "Pete Townshend", name: "Let My Love Open The Door", youtubeId: "9dw29xpA0Qg" },
  { artist: "Tokyo Machine", name: "Hype", youtubeId: "74Yir_AP2Ts" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "One Final Effort (Halo 3)", youtubeId: "5b8zZmSZC_0" },
  { artist: "Pat Benatar", name: "Shadows Of The Night", youtubeId: "J6hZ4NwFCg0" },
  { artist: "Pink Floyd", name: "Time", youtubeId: "pgXozIma-Oc" },
  { artist: "Dave Matthews Band", name: "Ants Marching", youtubeId: "nE5p3acSloM" },
  { artist: "Supertramp", name: "Goodbye Stranger", youtubeId: "u8pVZ5hTGJQ" },
  { artist: "Rob Thomas", name: "Lonely No More", youtubeId: "cg48698R0KA" },
  { artist: "Steve Miller Band", name: "The Joker", youtubeId: "tYTgtsCm0DA" },
  { artist: "Barenaked Ladies", name: "Pinch Me (Radio Version)", youtubeId: "udBWSiRL7yU" },
  { artist: "Foo Fighters", name: "Learn to Fly", youtubeId: "HJMLLKgknvk" },
  { artist: "[HD] The Protomen", name: "Act II", youtubeId: "gkLvpt9Z3fA" },
  { artist: "The Who", name: "Eminence Front", youtubeId: "BfrUQA2tb6M" },
  { artist: "Led Zeppelin", name: "Black Dog (Remaster)", youtubeId: "XIiu0JI3I5g" },
  { artist: "Rascal Flatts", name: "Life is a Highway", youtubeId: "Zh-ZUrc-aLI" },
  { artist: "Men At Work", name: "Down Under", youtubeId: "hfmxO-HQ5rU" },
  { artist: "Men At Work", name: "Who Can It Be Now?", youtubeId: "Lc1Ll-euRSg" },
  { artist: "The Outfield, John Frederick Spinks", name: "Colosseum", youtubeId: "EE-_HB-Z3sM" },
  { artist: "Pitbull, John Ryan", name: "Fireball", youtubeId: "AN2-czGsblw" },
  { artist: "Pink Floyd", name: "The Happiest Days Of Our Lives", youtubeId: "VyTarjUjNMQ" },
  { artist: "Pink Floyd", name: "On The Run", youtubeId: "2sUyk5zSbhM" },
  { artist: "Mark Morrison", name: "Return of the Mack", youtubeId: "1ZfjB5P7RS0" },
  { artist: "Mötley Crüe", name: "Kickstart My Heart", youtubeId: "WqOlHt--fOI" },
  { artist: "Foreigner", name: "I Want to Know What Love Is (2008 Remaster)", youtubeId: "3DpHXUuxq1Q" },
  { artist: "Justice", name: "Genesis", youtubeId: "VKzWLUQizz8" },
  { artist: "Marc Cohn", name: "Walking in Memphis", youtubeId: "dUh1DSIsUOY" },
  { artist: "Lady Gaga", name: "Poker Face", youtubeId: "oG-4Uvhm4lI" },
  { artist: "Home", name: "Resonance", youtubeId: "Qe2t3FyS9uA" },
  { artist: "Cutting Crew", name: "[I Just] Died In Your Arms", youtubeId: "2wf-MNzSbpA" },
  { artist: "Tom Petty And The Heartbreakers", name: "Learning To Fly", youtubeId: "zG5FPc-qDv0" },
  { artist: "Bronski Beat", name: "Smalltown Boy", youtubeId: "8PGppDW8kD0" },
  { artist: "M.C. Hammer", name: "U Can't Touch This", youtubeId: "gDCRrvtY78g" },
  { artist: "Madonna, Justin Timberlake, Timbaland", name: "4 Minutes (feat. Justin Timberlake and Timbaland)", youtubeId: "cySuerPVnQA" },
  { artist: "Styx", name: "Come Sail Away", youtubeId: "yhKe20WWLAY" },
  { artist: "Maroon 5", name: "Harder To Breathe", youtubeId: "Back4okF0Yg" },
  { artist: "Kungs, Cookin' On 3 Burners", name: "This Girl (Kungs Vs. Cookin' On 3 Burners)", youtubeId: "kNtk-CnpL-Y" },
  { artist: "Earth, Wind & Fire", name: "Let's Groove", youtubeId: "ltjio4AM2uw" },
  { artist: "Billy Squier", name: "The Stroke", youtubeId: "5KOUEX_oG9k" },
  { artist: "OK Go", name: "This Too Shall Pass", youtubeId: "jWsntzxlsPM" },
  { artist: "Nitro Fun", name: "Cheat Codes", youtubeId: "2Y9uceuIAxE" },
  { artist: "REO Speedwagon", name: "Can't Fight This Feeling", youtubeId: "z_WYwfrMFko" },
  { artist: "Skid Row", name: "Youth Gone Wild", youtubeId: "x6d07j_IL1M" },
  { artist: "Katy Perry", name: "Firework", youtubeId: "S23IzDZBuBQ" },
  { artist: "Steve Winwood", name: "The Finer Things", youtubeId: "aU4tFpwYK0s" },
  { artist: "Maroon 5", name: "She Will Be Loved", youtubeId: "LHBbWBX_azA" },
  { artist: "Bob Seger & The Silver Bullet Band", name: "Turn The Page (Live At Cobo Hall, Detriot/1975/Remaster 2011)", youtubeId: "twZZdk2OuDk" },
  { artist: "Nickelback", name: "Photograph", youtubeId: "LzejHuBS_D4" },
  { artist: "Caramella Girls", name: "Caramelldansen (Speedy Mixes)", youtubeId: "UwTt2Ox_0AE" },
  { artist: "Natalie Imbruglia", name: "Torn", youtubeId: "rIGAt5yvfmw" },
  { artist: "Of Monsters and Men", name: "Little Talks", youtubeId: "KtDmEy7R_c8" },
  { artist: "Eminem", name: "Lose Yourself (From \"8 Mile\" Soundtrack)", youtubeId: "Wj7lL6eDOqc" },
  { artist: "Cage The Elephant", name: "Ain't No Rest for the Wicked", youtubeId: "e2Z0sON2UPc" },
  { artist: "Kendrick Lamar", name: "HUMBLE", youtubeId: "ZZxHN6hpoeQ" },
  { artist: "ABBA", name: "Voulez-Vous", youtubeId: "0X2mn7Sk9lQ" },
  { artist: "Metro Station", name: "Shake It", youtubeId: "ED3Uc-GSgzY" },
  { artist: "Redbone", name: "Come and Get Your Love", youtubeId: "rsf_gTZG4cI" },
  { artist: "Bon Jovi", name: "Wanted Dead Or Alive", youtubeId: "xNRaDavYo1M" },
  { artist: "Daft Punk", name: "Technologic", youtubeId: "R5uHYAIkzgU" },
  { artist: "Iron Butterfly", name: "In-A-Gadda-Da-Vida", youtubeId: "Tfpn3wHoNGA" },
  { artist: "Prince & The Revolution", name: "Purple Rain", youtubeId: "S6Y1gohk5-A" },
  { artist: "Pink Floyd", name: "The Great Gig In The Sky", youtubeId: "mPGv8L3a_sY" },
  { artist: "Magic Sword", name: "In The Face Of Evil", youtubeId: "ZyHfUqs17WI" },
  { artist: "deadmau5 feat. Chris James", name: "The Veldt", youtubeId: "uiUAq4aVTjY" },
  { artist: "Sheryl Crow", name: "Soak Up The Sun", youtubeId: "88HeyQnV6Qk" },
  { artist: "Cheap Trick", name: "The Flame", youtubeId: "km0uoY9u5yk" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Brothers in Arms (Halo: Combat Evolved)", youtubeId: "aQHZCP0ew88" },
  { artist: "Sheryl Crow", name: "Real Gone", youtubeId: "HdimnI4Xtc0" },
  { artist: "Good Charlotte", name: "I Don't Wanna Be In Love (Dance Floor Anthem)", youtubeId: "jtePSuQB5S0" },
  { artist: "Elton John", name: "Tiny Dancer", youtubeId: "aqlGlaNlcWE" },
  { artist: "The Killers", name: "All These Things That I've Done", youtubeId: "AUAxlOfw2O0" },
  { artist: "Red Hot Chili Peppers", name: "Can't Stop", youtubeId: "D4INE2zO9OU" },
  { artist: "R.E.M.", name: "Everybody Hurts", youtubeId: "tKRznjaIIyw" },
  { artist: "Tom Petty And The Heartbreakers", name: "Don't Do Me Like That", youtubeId: "LwgY3qB7PBI" },
  { artist: "Mat Zo", name: "Caller ID", youtubeId: "bCx3wjP-2zQ" },
  { artist: "E-40", name: "Choices (Yup)", youtubeId: "UloQngR6kjQ" },
  { artist: "Van Halen", name: "Runnin' with the Devil (2015 Remaster)", youtubeId: "KLRO4W9pNrQ" },
  { artist: "Beastie Boys", name: "Fight For Your Right", youtubeId: "pYoN9OraOWM" },
  { artist: "Prince & The Revolution", name: "I Would Die 4 U", youtubeId: "hkNl3pq1twE" },
  { artist: "Linkin Park", name: "What I've Done", youtubeId: "Jrprk5dNboI" },
  { artist: "Daft Punk, Pharrell Williams, Nile Rodgers", name: "Get Lucky (feat. Pharrell Williams and Nile Rodgers)", youtubeId: "4D7u5KF7SP8" },
  { artist: "Quiet Riot", name: "Cum on Feel the Noize", youtubeId: "XQ5mygB97nM" },
  { artist: "Evanescence", name: "Bring Me To Life", youtubeId: "-eGM0IJc70Y" },
  { artist: "Bruce Springsteen", name: "Glory Days", youtubeId: "GLBnj159q3s" },
  { artist: "twenty one pilots", name: "Holding on to You", youtubeId: "_t8HWppY4T0" },
  { artist: "Linkin Park", name: "Numb", youtubeId: "u-IcadiJCrE" },
  { artist: "ABBA", name: "Waterloo", youtubeId: "9y-8ZiAJiQo" },
  { artist: "M.O.O.N.", name: "'Crystals' [Hotline Miami Soundtrack]", youtubeId: "AVblOqZBlJw" },
  { artist: "Sugar High", name: "Approaching Nirvana", youtubeId: "ngsGBSCDwcI" },
  { artist: "Toto", name: "Rosanna", youtubeId: "SGtVZgCYVgk" },
  { artist: "Pet Shop Boys", name: "West End Girls (2001 Remaster)", youtubeId: "-G8KmNF-xc4" },
  { artist: "Daryl Hall & John Oates", name: "I Can't Go for That (No Can Do)", youtubeId: "Ry04tCx4Bqw" },
  { artist: "Spin Doctors", name: "Two Princes", youtubeId: "a748-dgSB10" },
  { artist: "Def Leppard", name: "Hysteria", youtubeId: "FXjyoArp3ZE" },
  { artist: "Will Smith, Dru Hill, Kool Mo Dee", name: "Wild Wild West", youtubeId: "vRLED8AvVvQ" },
  { artist: "311", name: "Stealing Happy Hours", youtubeId: "P22-e4Ol49s" },
  { artist: "Pitbull, Ke$ha", name: "Timber", youtubeId: "GcYF1xnmZTI" },
  { artist: "Kevin Rudolf, Lil Wayne", name: "Let It Rock", youtubeId: "1lAdfEsf4p8" },
  { artist: "Joe \"Bean\" Esposito", name: "You're The Best (The Karate Kid)", youtubeId: "p44G0U4sLCE" },
  { artist: "Barenaked Ladies", name: "If I Had $1,000,000", youtubeId: "aynCgnbbgbM" },
  { artist: "Chris Tilton", name: "Building the Foundation (SimCity 2013)", youtubeId: "d_QvSN07S5c" },
  { artist: "Pearl Jam", name: "Even Flow", youtubeId: "u7T2OR-O2Vk" },
  { artist: "LMFAO, Lauren Bennett, GoonRock", name: "Party Rock Anthem", youtubeId: "wO2TLZ6Pqo4" },
  { artist: "Deadmau5", name: "Strobe (Club Edit)", youtubeId: "oUmvPgH5iD0" },
  { artist: "Bee Gees", name: "You Should Be Dancing", youtubeId: "4Qhe7aXeY4g" },
  { artist: "Huey Lewis & The News", name: "The Power Of Love", youtubeId: "wIiVp3poe2c" },
  { artist: "Van Halen", name: "Ain't Talkin' 'Bout Love (2015 Remaster)", youtubeId: "qtwBFz6lfrY" },
  { artist: "Kenji Niinuma", name: "The Moon and the Prince (Katamari Damacy)", youtubeId: "pUJeiEva0Hw" },
  { artist: "Rob Thomas", name: "Little Wonders", youtubeId: "GpSYDmYZgkA" },
  { artist: "MACINTOSH PLUS", name: "リサフランク420 / 現代のコンピュー", youtubeId: "aQkPcPqTq4M" },
  { artist: "Pink Floyd", name: "Breathe (In The Air)", youtubeId: "Vddl9TK5RqU" },
  { artist: "2Pac, Roger Troutman, Dr. Dre", name: "California Love (Original Version)", youtubeId: "LRt6TdSvHag" },
  { artist: "Thomas Bergersen", name: "Protectors of the Earth", youtubeId: "Y54rf5FfO90" },
  { artist: "Eric Clapton", name: "I Shot The Sheriff", youtubeId: "L0xLLPJ0bOw" },
  { artist: "Savage Garden", name: "Truly Madly Deeply", youtubeId: "5lGqXIiDxFM" },
  { artist: "Eric Johnson", name: "Cliffs Of Dover (Instrumental)", youtubeId: "wpAC1vr_pcg" },
  { artist: "Prince", name: "Little Red Corvette (2019 Remaster)", youtubeId: "OUZyb7YeEYA" },
  { artist: "Michael Jackson", name: "Rock with You", youtubeId: "OvzJZTkWYoY" },
  { artist: "Bryan Adams", name: "(Everything I Do) I Do It For You", youtubeId: "Y0pdQU87dc8" },
  { artist: "Barenaked Ladies", name: "Odds Are", youtubeId: "FrMdoHrKspE" },
  { artist: "Modjo", name: "Lady (Hear Me Tonight)", youtubeId: "MR3uP7IYz44" },
  { artist: "Depeche Mode", name: "Just Can't Get Enough", youtubeId: "yI_DKk3mxOI" },
  { artist: "Cypis", name: "Gdzie jest biały węgorz ? (Zejście)", youtubeId: "nVxGcpBdk5k" },
  { artist: "Flobots", name: "Handlebars", youtubeId: "3w0qD6Atvo4" },
  { artist: "Airbourne", name: "Back In The Game", youtubeId: "FlPalDkWsuA" },
  { artist: "Big Giant Circles", name: "Vindicate Me", youtubeId: "-0LjT-mMBSU" },
  { artist: "Daft Punk, Pharrell Williams", name: "Lose Yourself to Dance (feat. Pharrell Williams)", youtubeId: "iU7oF4OXZSE" },
  { artist: "AC/DC", name: "Hells Bells", youtubeId: "etAIpkdhU9Q" },
  { artist: "KC & The Sunshine Band", name: "That's the Way (I Like It) (2004 Remaster)", youtubeId: "aXxB2QN2IuY" },
  { artist: "The Knack", name: "My Sharona", youtubeId: "ZR-3r5Z9kqw" },
  { artist: "Hollywood Principle, Kev Frey", name: "Seeing What's Next (Kev Frey Remix)", youtubeId: "JFRAatKpGII" },
  { artist: "Fleetwood Mac", name: "The Chain (2004 Remaster)", youtubeId: "FhgFtXESdPk" },
  { artist: "Chic", name: "Le Freak", youtubeId: "RAYQTfFh4xk" },
  { artist: "John Parr", name: "St. Elmos Fire (Man in Motion)", youtubeId: "or20Ovv0Mag" },
  { artist: "Foo Fighters", name: "Best of You", youtubeId: "L6SIgRlijmU" },
  { artist: "Tay Zonday", name: "Chocolate Rain", youtubeId: "k7vJPCkOmx8" },
  { artist: "Fleetwood Mac", name: "Little Lies (2017 Remaster)", youtubeId: "ZWuViMR_A1o" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Heretic, Hero (Halo 2)", youtubeId: "0ZpyKvLB_Ec" },
  { artist: "Skid Row", name: "18 and Life (2016 Remaster)", youtubeId: "wwQWJnVREZ0" },
  { artist: "Billy Idol", name: "White Wedding (Pt. 1)", youtubeId: "o5oTrvdNoP4" },
  { artist: "Coldplay", name: "Clocks", youtubeId: "PFW2uSCZ0uE" },
  { artist: "Fleetwood Mac", name: "Dreams (2004 Remaster)", youtubeId: "swJOIjjW69U" },
  { artist: "The Script, will.i.am", name: "Hall of Fame", youtubeId: "3Nn4JqTNB9g" },
  { artist: "John Mellencamp", name: "Cherry Bomb", youtubeId: "ll8YLkromVc" },
  { artist: "twenty one pilots", name: "Heavydirtysoul", youtubeId: "lzXRdS9cynQ" },
  { artist: "Martin O’Donnell, Michael Salvatori, Stan LePard", name: "Skyline (Halo 3: ODST)", youtubeId: "IHxFTQYAqfc" },
  { artist: "Savant", name: "Laser Sharks (Original Mix)", youtubeId: "21BgQj2sVeI" },
  { artist: "The Rolling Stones", name: "Gimme Shelter", youtubeId: "RbmS3tQJ7Os" },
  { artist: "Jeff D. Elliott", name: "Top Secret", youtubeId: "okHAnJHdLwM" },
  { artist: "Tesla", name: "Signs", youtubeId: "w0NyH52NSms" },
  { artist: "Linkin Park", name: "CASTLE OF GLASS", youtubeId: "x2umzqh8r4g" },
  { artist: "Badfinger", name: "Day After Day", youtubeId: "-IiWtFY-vGE" },
  { artist: "Harry Chapin", name: "Cat's in the Cradle", youtubeId: "jmhoOp2fUzg" },
  { artist: "No Doubt", name: "Hella Good", youtubeId: "u6Gsv7BjYPQ" },
  { artist: "Guns N' Roses", name: "Paradise City", youtubeId: "T0ZmErXkbxE" },
  { artist: "Of Monsters and Men", name: "Empire", youtubeId: "9Wa7Ok7RXvE" },
  { artist: "Tom Petty", name: "I Won't Back Down", youtubeId: "Is4uUP11NxE" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Neon Night (Halo 3: ODST)", youtubeId: "VoyyNpRC3Eg" },
  { artist: "Goo Goo Dolls", name: "Slide", youtubeId: "KXRKoM0misA" },
  { artist: "Will Smith", name: "Gettin' Jiggy Wit It", youtubeId: "5VPm2yckO3k" },
  { artist: "Van Halen", name: "Jump", youtubeId: "bX9RMdcFQAw" },
  { artist: "Earth, Wind & Fire, The Emotions", name: "Boogie Wonderland", youtubeId: "2Hp8adWkSFU" },
  { artist: "Will Smith", name: "Men In Black (From \"Men In Black\" Soundtrack)", youtubeId: "fzMXRGroHGk" },
  { artist: "Golden Earring", name: "Twilight Zone", youtubeId: "HOuc0kuKRV4" },
  { artist: "Nine Days", name: "Absolutely (Story of a Girl) (Radio Mix)", youtubeId: "ZwHMBZ34eQQ" },
  { artist: "Otis McDonald", name: "Not For Nothing", youtubeId: "mGpXOasfFkE" },
  { artist: "Michael Jackson", name: "Man in the Mirror (2012 Remaster)", youtubeId: "8gqMRlN6mAA" },
  { artist: "Madonna", name: "Papa Don't Preach", youtubeId: "spsbYZ3y83E" },
  { artist: "Deniece Williams", name: "Let's Hear It for the Boy (From \"Footloose\" Soundtrack)", youtubeId: "vwXx5BgXyJ8" },
  { artist: "Taco, Irving Berlin, Irving Berlin", name: "Puttin' on the Ritz", youtubeId: "TMstTM01m28" },
  { artist: "Pink Floyd", name: "Run Like Hell", youtubeId: "j2s8yGMEbSs" },
  { artist: "R.E.M.", name: "Losing My Religion", youtubeId: "Efa6BAWPm9o" },
  { artist: "No Doubt", name: "Just A Girl", youtubeId: "liSwJDJtmPw" },
  { artist: "Madness", name: "Our House", youtubeId: "r0KzvXf-_Zw" },
  { artist: "Van Halen", name: "Why Can't This Be Love", youtubeId: "ybbfEzKfpts" },
  { artist: "Michelle Branch", name: "Everywhere", youtubeId: "UCzLhySDWME" },
  { artist: "Sixpence None The Richer", name: "Kiss Me", youtubeId: "K2tbQ_g2VbQ" },
  { artist: "Barenaked Ladies", name: "The Old Apartment", youtubeId: "Pv7kodfFXpA" },
  { artist: "Pitbull", name: "I Know You Want Me (Calle Ocho) (Radio Edit)", youtubeId: "P7sbjPggfkU" },
  { artist: "Dido", name: "Thank You", youtubeId: "1TO48Cnl66w" },
  { artist: "Noisestorm", name: "Crab Rave", youtubeId: "c_sNBS-9Ras" },
  { artist: "Savant", name: "Splinter (Original Mix)", youtubeId: "TdBGb6vB9nU" },
  { artist: "The Chemical Brothers", name: "Star Guitar", youtubeId: "0S43IwBF0uM" },
  { artist: "Breaking Benjamin", name: "Blow Me Away (Halo 2)", youtubeId: "tj9QbiBaSsk" },
  { artist: "Boston", name: "Rock & Roll Band", youtubeId: "n-pC3ncVjEw" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "On a Pale Horse (Halo: Combat Evolved)", youtubeId: "cvaEIiboA8w" },
  { artist: "Genesis", name: "That's All (2007 Remaster)", youtubeId: "0X0EsVa7YvY" },
  { artist: "Nelly Furtado", name: "I'm Like A Bird", youtubeId: "QPvpSMkQsO4" },
  { artist: "Cascada", name: "Everytime We Touch", youtubeId: "84sHTvn6xf8" },
  { artist: "Led Zeppelin", name: "Immigrant Song (Remaster)", youtubeId: "5eHkjPCGXKQ" },
  { artist: "The Cars", name: "Just What I Needed", youtubeId: "TB4gJ7shVD0" },
  { artist: "The Police", name: "Roxanne", youtubeId: "fZheUzgIFEk" },
  { artist: "RUN DMC", name: "It's Tricky", youtubeId: "KB6SILem5Xs" },
  { artist: "Rick Astley", name: "Never Gonna Give You Up", youtubeId: "dQw4w9WgXcQ" },
  { artist: "Foreigner", name: "Cold as Ice (2008 Remaster)", youtubeId: "SdOFadTTV_8" },
  { artist: "Måns Zelmerlöw", name: "Heroes", youtubeId: "oqMi3IjaqqE" },
  { artist: "C418", name: "Droopy Likes Ricochet (Minecraft)", youtubeId: "9jlVL4syx8k" },
  { artist: "Bob Seger", name: "Shakedown", youtubeId: "uS-EGbXU_Fw" },
  { artist: "Big Giant Circles", name: "Go for Distance", youtubeId: "VGg05WGHThQ" },
  { artist: "The Alan Parsons Project", name: "Sirius", youtubeId: "OkC_oi0ksuw" },
  { artist: "Phil Collins", name: "Sussudio (2016 Remastered)", youtubeId: "5soq6RLoIz8" },
  { artist: "Pegboard Nerds", name: "Try This", youtubeId: "GIK5VWI_iqM" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Truth and Reconciliation Suite (Halo: Combat Evolved)", youtubeId: "lj91a6W91J8" },
  { artist: "Foghat", name: "Slow Ride", youtubeId: "T4287tw_dwk" },
  { artist: "The Revivalists", name: "Wish I Knew You", youtubeId: "ZMtw1n8tL4I" },
  { artist: "Matchbox Twenty", name: "She's so Mean", youtubeId: "KCdPYV9bLPI" },
  { artist: "REO Speedwagon", name: "Take It On the Run", youtubeId: "NVtIgfqI6yo" },
  { artist: "Eminem", name: "The Real Slim Shady", youtubeId: "r5MR7_INQwg" },
  { artist: "Led Zeppelin", name: "Kashmir (1990 Remaster)", youtubeId: "SsaFBNvhceA" },
  { artist: "Chicago", name: "Saturday in the Park (2002 Remaster)", youtubeId: "JPOF31V-Xwg" },
  { artist: "No Doubt", name: "Spiderwebs", youtubeId: "UBVEie8bNdE" },
  { artist: "Sam & Dave", name: "Hold On, I'm Coming", youtubeId: "6JElrEbAcwY" },
  { artist: "blink-182", name: "All The Small Things", youtubeId: "5_PBNZXlzp0" },
  { artist: "Red Hot Chili Peppers", name: "Give It Away", youtubeId: "XhjqmAoBKCQ" },
  { artist: "New Order", name: "Blue Monday (2016 Remaster)", youtubeId: "iOEJHNZpeck" },
  { artist: "Papa Roach", name: "Last Resort", youtubeId: "j2R6uT7uLFg" },
  { artist: "Aqua", name: "Barbie Girl", youtubeId: "77zog6Up_Yg" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Asphalt, Ablution (Halo 3: ODST)", youtubeId: "luzfzTy_bso" },
  { artist: "Frankie Goes To Hollywood", name: "Relax", youtubeId: "pJ2L1dh-dSo" },
  { artist: "Phil Collins", name: "In The Air Tonight", youtubeId: "y7f0x_UFfJE" },
  { artist: "Aerosmith", name: "Dream On", youtubeId: "89dGC8de0CA" },
  { artist: "Seal", name: "Crazy", youtubeId: "L0NoJi8omqc" },
  { artist: "Talking Heads", name: "Psycho Killer (2005 Remaster)", youtubeId: "tqQGWhge5yo" },
  { artist: "SEGA, Kensuke Inage, 荒井 善博, 吉田 真理, Kensuke Inage", name: "Friday Night (Yakuza 0)", youtubeId: "JHbDuuCoWxk" },
  { artist: "The Avalanches", name: "Because I’m Me", youtubeId: "NynnApj2smY" },
  { artist: "Donna Summer", name: "She Works Hard For The Money", youtubeId: "09ZSKE38lTU" },
  { artist: "Cher", name: "Gypsys, Tramps & Thieves", youtubeId: "bv-o_24MZfU" },
  { artist: "Nitro Fun", name: "New Game", youtubeId: "ZVkPmLt1qrM" },
  { artist: "Journey", name: "Who's Crying Now", youtubeId: "X5pJYBjcKeI" },
  { artist: "The Clash", name: "Rock the Casbah", youtubeId: "0pCFVX6lzHU" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Traffic Jam (Halo 3: ODST)", youtubeId: "kOa9FXAKA2o" },
  { artist: "OK Go", name: "Needing/Getting", youtubeId: "MejbOFk7H6c" },
  { artist: "Duran Duran", name: "The Reflex (2010 Remaster)", youtubeId: "xl_mWGyEUm8" },
  { artist: "PINK GUY", name: "STFU", youtubeId: "OLpeX4RRo28" },
  { artist: "Princeton", name: "LvUrFR3NZ (Halo 3)", youtubeId: "P4tEHl_P98E" },
  { artist: "KC & The Sunshine Band", name: "Boogie Shoes", youtubeId: "x8CthqzCgP4" },
  { artist: "Piano Fantasia, Serge Bijaoui, Thierry Durbet, Mike Serbee, Tidi", name: "Song for Denise (Maxi Version)", youtubeId: "hH9M-m3WD0g" },
  { artist: "Michael Jackson", name: "Beat It", youtubeId: "kOn-HdEg6AQ" },
  { artist: "Looking Glass", name: "Brandy (You're a Fine Girl)", youtubeId: "CFhFyvk0yS8" },
  { artist: "Nickelback", name: "This Afternoon", youtubeId: "nsxFrIAxdHQ" },
  { artist: "Michael Jackson", name: "Wanna Be Startin' Somethin'", youtubeId: "8KWf_-ofYgI" },
  { artist: "Smash Mouth", name: "I'm A Believer (From \"Shrek\" Motion Picture Soundtrack)", youtubeId: "xCP7bCJxxm8" },
  { artist: "Daler Mehndi", name: "Tunak Tunak Tun", youtubeId: "_T_MOxNGsks" },
  { artist: "Rihanna", name: "Disturbia", youtubeId: "wmGjajXDHKo" },
  { artist: "Mord Fustang", name: "Diamonds", youtubeId: "Ew-JkxeXvB0" },
  { artist: "Pink Floyd", name: "Hey You", youtubeId: "soL8JK6kALc" },
  { artist: "Foreigner", name: "Urgent (2008 Remaster)", youtubeId: "XIATjH1AxVc" },
  { artist: "Bon Jovi", name: "You Give Love A Bad Name", youtubeId: "Aqc3VTpz9HQ" },
  { artist: "TheFatRat", name: "Infinite Power", youtubeId: "twCzH75C_WE" },
  { artist: "Foreigner", name: "Feels like the First Time", youtubeId: "cDUEMvCKLis" },
  { artist: "The Black Keys", name: "Gold on the Ceiling", youtubeId: "8tPsaSPraks" },
  { artist: "Don Henley", name: "The Boys Of Summer", youtubeId: "6RUIeX6UCT8" },
  { artist: "Duran Duran", name: "Hungry Like the Wolf (2001 Remaster)", youtubeId: "qCeyLsDHsKk" },
  { artist: "Empire Of The Sun", name: "We Are The People", youtubeId: "r02mYOlfcCw" },
  { artist: "Lee Ann Womack", name: "I Hope You Dance", youtubeId: "ozR3XL4cab0" },
  { artist: "Vanessa Carlton", name: "A Thousand Miles", youtubeId: "PNoIn1WKiEc" },
  { artist: "Styx", name: "Babe", youtubeId: "ogicte-_dwA" },
  { artist: "Led Zeppelin", name: "Whole Lotta Love (Remaster)", youtubeId: "0bcIjILqORM" },
  { artist: "Evanescence", name: "My Immortal", youtubeId: "RxrTVf2vkLs" },
  { artist: "Hot Chelle Rae, New Boyz", name: "I Like It Like That", youtubeId: "Xvs5YJ7-two" },
  { artist: "Tom Petty", name: "Runnin' Down A Dream", youtubeId: "XrzeL7SK5Fw" },
  { artist: "Guns N' Roses", name: "Sympathy For The Devil", youtubeId: "ldCbVPMzyD4" },
  { artist: "Golden Earring", name: "Radar Love", youtubeId: "GyAvXV1NJNY" },
  { artist: "Lindsey Stirling", name: "Electric Daisy Violin", youtubeId: "XRSIZbqKs-A" },
  { artist: "Michelle Branch", name: "Breathe", youtubeId: "DgRhOuOibV4" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Unyielding (Halo 2)", youtubeId: "xYuxrYdL-D0" },
  { artist: "Dire Straits", name: "Walk of Life", youtubeId: "hylE_GwLFCM" },
  { artist: "The Ozark Mountain Daredevils", name: "Jackie Blue", youtubeId: "6xuW-aI-haw" },
  { artist: "Don McLean", name: "American Pie", youtubeId: "iX_TFkut1PM" },
  { artist: "Third Eye Blind", name: "Jumper (1998 Edit)", youtubeId: "tjK8zK3TMJc" },
  { artist: "TheFatRat", name: "Unity", youtubeId: "P7nF7jXF-Jg" },
  { artist: "Rihanna, Calvin Harris", name: "We Found Love", youtubeId: "UUpuyzPJeWA" },
  { artist: "Guns N' Roses", name: "Patience", youtubeId: "MkoeqtKUUe4" },
  { artist: "El Chombo", name: "Chacarrón", youtubeId: "omkF2Rdnfj4" },
  { artist: "Simon & Garfunkel", name: "The Sound of Silence (Electric Version)", youtubeId: "bjkPQYWNTlg" },
  { artist: "Toto", name: "I Won't Hold You Back", youtubeId: "rQysrhYnWHg" },
  { artist: "Smash Mouth", name: "All Star", youtubeId: "8ay_BkRuv-o" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Greatest Journey (Halo 3)", youtubeId: "4Q0Jbv6ciRU" },
  { artist: "Shania Twain", name: "Honey, I'm Home", youtubeId: "a-P-bcMbK1I" },
  { artist: "Hyper Potions", name: "Friends (Sonic Mania)", youtubeId: "h4JK-j_b1BQ" },
  { artist: "Paul Engemann", name: "Scarface (Push It To The Limit)", youtubeId: "TgHi0LxiPfg" },
  { artist: "Martin O’Donnell, Michael Salvatori, Stan LePard", name: "The Menagerie (Halo 3: ODST)", youtubeId: "So1nJcCFWfw" },
  { artist: "Bryan Adams", name: "Summer Of '69", youtubeId: "eFjjO_lhf9c" },
  { artist: "REO Speedwagon", name: "Keep on Loving You", youtubeId: "XKc7z-enzmA" },
  { artist: "Don Omar, Lucenzo", name: "Danza Kuduro", youtubeId: "BbWY-avjDto" },
  { artist: "Panic! At The Disco", name: "I Write Sins Not Tragedies", youtubeId: "Vy0mqXuBMY4" },
  { artist: "Toby Fox", name: "Field of Hopes and Dreams (Deltarune)", youtubeId: "ymNgfwgh1TU" },
  { artist: "Commuter", name: "Young Hearts (The Karate Kid)", youtubeId: "ziL-jORBF_M" },
  { artist: "Bee Gees", name: "Tragedy", youtubeId: "qzNDY1VknaQ" },
  { artist: "Genesis", name: "Invisible Touch", youtubeId: "rlD0XQibpaY" },
  { artist: "Vanilla Ice", name: "Ice Ice Baby", youtubeId: "jewmMjnbfzE" },
  { artist: "Mountain", name: "Mississippi Queen", youtubeId: "VbP4qf8PjfI" },
  { artist: "twenty one pilots", name: "Hometown", youtubeId: "wS8otCVxpkw" },
  { artist: "Franz Ferdinand", name: "Take Me Out", youtubeId: "d11xns8lE4w" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Reclaimer (Halo 2)", youtubeId: "yaOqNSjaca4" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Behold a Pale Horse (Halo 3)", youtubeId: "zJUuMk18sqQ" },
  { artist: "Santana", name: "Black Magic Woman", youtubeId: "9wT1s96JIb0" },
  { artist: "Gwen Stefani, Akon", name: "The Sweet Escape", youtubeId: "BsqG3_FpRzE" },
  { artist: "ABBA", name: "Mamma Mia", youtubeId: "KMViJKmAV4M" },
  { artist: "Five for Fighting", name: "Superman (It's Not Easy)", youtubeId: "GRz4FY0ZcwI" },
  { artist: "Can't Stop Won't Stop", name: "Cool Summer", youtubeId: "0NeVgwY0wJc" },
  { artist: "Rise Against", name: "Savior", youtubeId: "vbMh38KGZMM" },
  { artist: "Enrique Iglesias", name: "Bailamos", youtubeId: "npzWrl7jn88" },
  { artist: "Rick James", name: "Super Freak", youtubeId: "wnKc4zi0MLA" },
  { artist: "Third Eye Blind", name: "Never Let You Go", youtubeId: "2nroaoWEXIA" },
  { artist: "Herman's Hermits", name: "I'm Into Something Good", youtubeId: "MDUCOwp1p60" },
  { artist: "Van Halen", name: "Runnin' with the Devil (2015 Remaster)", youtubeId: "enL_lzVyNdM" },
  { artist: "Sammy Hagar", name: "I Can't Drive 55", youtubeId: "2Qf98egLWOk" },
  { artist: "Talking Heads", name: "Road to Nowhere (2005 Remaster)", youtubeId: "FhRLGarxEuY" },
  { artist: "Pat Benatar", name: "Love Is A Battlefield", youtubeId: "vo6PgC0cP4c" },
  { artist: "Boston", name: "More Than a Feeling", youtubeId: "ufQUxoidxkM" },
  { artist: "Daryl Hall & John Oates", name: "You Make My Dreams (Come True)", youtubeId: "E4CZuj7solw" },
  { artist: "War", name: "Low Rider", youtubeId: "qMkwuz0iXQg" },
  { artist: "R.E.M.", name: "Shiny Happy People", youtubeId: "nsI2BdCmoCA" },
  { artist: "The Outfield", name: "Your Love", youtubeId: "W2a8Ng1qM8Q" },
  { artist: "Creedence Clearwater Revival", name: "Born On The Bayou", youtubeId: "Exu8w2sp2Gg" },
  { artist: "Eminem, Dido", name: "Stan", youtubeId: "HIqQ0PfuPo8" },
  { artist: "Neil Diamond", name: "Brother Love's Travelling Salvation Show", youtubeId: "6pCxPNuokfM" },
  { artist: "Jordin Sparks", name: "One Step At a Time", youtubeId: "1WDmCPTlC3k" },
  { artist: "The Cult", name: "She Sells Sanctuary", youtubeId: "cQS4TzB0EvU" },
  { artist: "Steve Miller Band", name: "Jungle Love", youtubeId: "qGnCyMc_X-4" },
  { artist: "Talking Heads", name: "Burning Down the House (2005 Remaster)", youtubeId: "bgJ-hyzl6jg" },
  { artist: "Santana, Rob Thomas", name: "Smooth", youtubeId: "mom2TLs3Fi0" },
  { artist: "Bon Jovi", name: "It's My Life", youtubeId: "bY3vXr7fm8k" },
  { artist: "Eminem", name: "Without Me", youtubeId: "9SbT3q1a6dQ" },
  { artist: "Bee Gees", name: "More Than A Woman", youtubeId: "ki5i2oxD2Eg" },
  { artist: "Barenaked Ladies", name: "One Week", youtubeId: "gES4Z1ll9nI" },
  { artist: "deadmau5 feat. Rob Swire", name: "Monophobia", youtubeId: "NESCd6IFfLM" },
  { artist: "Dolly Parton", name: "9 to 5", youtubeId: "E4OzdyxbOuU" },
  { artist: "James Taylor", name: "Fire and Rain", youtubeId: "N8u8tASPtwg" },
  { artist: "The Bellamy Brothers", name: "Let Your Love Flow", youtubeId: "LzXz6-RXXgc" },
  { artist: "The Fratellis", name: "Chelsea Dagger", youtubeId: "2gDb_axpfeY" },
  { artist: "Bay City Rollers", name: "Saturday Night", youtubeId: "csXFpFoRkEk" },
  { artist: "Tina Charles", name: "I Love to Love", youtubeId: "RDbL8GLr1yw" },
  { artist: "The Trammps", name: "Disco Inferno (Edit)", youtubeId: "pG8TyIEAqps" },
  { artist: "Duck Sauce", name: "Barbra Streisand (Original Mix)", youtubeId: "nTx_1rli-Lw" },
  { artist: "Chicago", name: "25 or 6 to 4", youtubeId: "JTzFh1dCoGg" },
  { artist: "R.E.M.", name: "The One I Love", youtubeId: "pBHBuFqy6I8" },
  { artist: "Simple Minds", name: "Don't You (Forget About Me)", youtubeId: "Ly61QG9yWOc" },
  { artist: "Peter Bjorn and John", name: "Young Folks", youtubeId: "OIRE6iw-ws4" },
  { artist: "America", name: "A Horse with No Name", youtubeId: "mSZXWdKSQNM" },
  { artist: "Pink Floyd", name: "Comfortably Numb", youtubeId: "x-xTttimcNk" },
  { artist: "Status Quo", name: "Rockin' All Over The World", youtubeId: "1cJGL9qEYUE" },
  { artist: "twenty one pilots", name: "Jumpsuit", youtubeId: "YTPAHj4bPjA" },
  { artist: "Tom Petty And The Heartbreakers", name: "Refugee", youtubeId: "8vDgheSFX04" },
  { artist: "Pink Guy", name: "Nickelodeon Girls", youtubeId: "pgVIL0mo6yA" },
  { artist: "Michael Jackson", name: "Thriller", youtubeId: "Z85lxckrtzg" },
  { artist: "Justice", name: "DVNO", youtubeId: "eLOtl3nLR7Q" },
  { artist: "Derek & The Dominos", name: "Layla", youtubeId: "TngViNw2pOo" },
  { artist: "Katy Perry", name: "E.T.", youtubeId: "We1Oe59I9Os" },
  { artist: "Wolfmother", name: "Joker And The Thief", youtubeId: "iR5RY7pnMGI" },
  { artist: "Matthew Wilder", name: "Break My Stride", youtubeId: "UhLDA4Wr2GU" },
  { artist: "The Bangles", name: "Walk Like an Egyptian", youtubeId: "cFGCu5hnLyA" },
  { artist: "Billy Idol", name: "Rebel Yell", youtubeId: "seHlHzYpWBU" },
  { artist: "Jack Johnson", name: "Upside Down", youtubeId: "e2vLWbaOITw" },
  { artist: "Tom Petty And The Heartbreakers", name: "You Got Lucky", youtubeId: "ZzN1pM_5-Eo" },
  { artist: "White Town", name: "Your Woman", youtubeId: "3NoIusrv9OA" },
  { artist: "Rod Stewart", name: "Young Turks", youtubeId: "EbZP13EbpgM" },
  { artist: "George Harrison", name: "When We Was Fab", youtubeId: "wlIKlyjpvYw" },
  { artist: "Warren G, Nate Dogg", name: "Regulate", youtubeId: "a02YJhCeTQk" },
  { artist: "Maroon 5", name: "This Love", youtubeId: "AqQuRw0S6b4" },
  { artist: "Counting Crows", name: "Mr. Jones", youtubeId: "x_dtKRzbCTU" },
  { artist: "Rush", name: "YYZ", youtubeId: "ScaPlYMgwTU" },
  { artist: "Survivor", name: "Burning Heart (From \"Rocky IV\" Soundtrack)", youtubeId: "Nm7AA78Vq8o" },
  { artist: "Don Henley", name: "All She Wants To Do Is Dance", youtubeId: "wFBHBSPvZbw" },
  { artist: "Cascada", name: "Evacuate The Dancefloor (Radio Edit)", youtubeId: "MrhgWddbVNk" },
  { artist: "Free", name: "All Right Now", youtubeId: "qBj5zJjHoSk" },
  { artist: "Vertical Horizon", name: "Everything You Want", youtubeId: "FwTQOPZvY3s" },
  { artist: "Ben Folds", name: "Rockin' the Suburbs", youtubeId: "nD30KV26ivg" },
  { artist: "Alphaville", name: "Forever Young", youtubeId: "W5guhMw_EH0" },
  { artist: "Daft Punk", name: "Around the World", youtubeId: "-0srGzIW_5w" },
  { artist: "Led Zeppelin", name: "Stairway to Heaven (Remaster)", youtubeId: "iXQUu5Dti4g" },
  { artist: "Pink Guy", name: "Gays 4 Donald", youtubeId: "uX9HfGwomBk" },
  { artist: "Foreigner", name: "Juke Box Hero (2008 Remaster)", youtubeId: "UG9VTg3aHS8" },
  { artist: "Roxette", name: "The Look", youtubeId: "-1lHYs--Pik" },
  { artist: "REO Speedwagon", name: "Roll with the Changes", youtubeId: "m1ml05Ty5Ao" },
  { artist: "WALK THE MOON", name: "Shut Up and Dance", youtubeId: "GGsuLVlLObc" },
  { artist: "Lynyrd Skynyrd", name: "Free Bird", youtubeId: "CqnU_sJ8V-E" },
  { artist: "Tal Bachman", name: "She's so High", youtubeId: "jmB9-99_9Y8" },
  { artist: "Bon Jovi", name: "Bad Medicine", youtubeId: "AfI1QznxY5c" },
  { artist: "House Of Pain", name: "Jump Around (30 Years Remaster)", youtubeId: "Ps402yYQIm0" },
  { artist: "AC/DC", name: "Highway to Hell", youtubeId: "l482T0yNkeo" },
  { artist: "Paula Abdul", name: "Straight Up", youtubeId: "V26f420X9r4" },
  { artist: "Greg Kihn Band", name: "Jeopardy", youtubeId: "5iZSlA4s5Xs" },
  { artist: "Guns N' Roses", name: "November Rain", youtubeId: "y6lfK3bH4z8" },
  { artist: "Matchbox Twenty", name: "3AM", youtubeId: "hH4wcNRj9PI" },
  { artist: "glue70", name: "Casin", youtubeId: "fZUm1mwtk5I" },
  { artist: "AJR", name: "Burn The House Down", youtubeId: "tsODB-N84WY" },
  { artist: "LMFAO", name: "Sexy And I Know It", youtubeId: "NqiTCzvTk6I" },
  { artist: "Def Leppard", name: "Pour Some Sugar On Me", youtubeId: "Rqs4cMyMLnY" },
  { artist: "Katy Perry", name: "Hot N Cold", youtubeId: "C-jAPrdc3PI" },
  { artist: "Snow Patrol", name: "Chasing Cars", youtubeId: "sgj04v5sDm4" },
  { artist: "Naked Eyes", name: "Promises, Promises", youtubeId: "GaGr010ey5U" },
  { artist: "John Mayer", name: "No Such Thing", youtubeId: "0LWAGLMBB2M" },
  { artist: "Pink Guy", name: "Goofy's Trial", youtubeId: "ZvftpofBzZE" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Perilous Journey (Halo: Combat Evolved)", youtubeId: "0obow-wqPb0" },
  { artist: "Billy Squier", name: "Lonely Is The Night", youtubeId: "C5TaeDhPUQQ" },
  { artist: "The Heavy", name: "How You Like Me Now", youtubeId: "PgeluJltn8w" },
  { artist: "Michelle Branch", name: "All You Wanted", youtubeId: "54GTRiMDOYA" },
  { artist: "John Mellencamp", name: "R.O.C.K. In The U.S.A.", youtubeId: "NI4yOx6XGdM" },
  { artist: "Supergrass", name: "Alright", youtubeId: "2QrYNgjuBJc" },
  { artist: "The Last Goodnight", name: "Pictures Of You", youtubeId: "zmUtXrDBVtE" },
  { artist: "Laszlo", name: "Supernova", youtubeId: "G-gzY6P33UQ" },
  { artist: "The Weeknd", name: "Blinding Lights", youtubeId: "J7p4bzqLvCw" },
  { artist: "Matchbox Twenty", name: "Real World", youtubeId: "8u8gnS1hqiM" },
  { artist: "Chumbawamba", name: "Tubthumping", youtubeId: "yW5oTzftgjY" },
  { artist: "Mike Posner", name: "Cooler Than Me (Single Mix)", youtubeId: "Bsr8hb3TPBI" },
  { artist: "Los Del Rio", name: "Macarena (Bayside Boys Remix)", youtubeId: "zWaymcVmJ-A" },
  { artist: "Toby Fox", name: "Dummy! (Undertale)", youtubeId: "94JDIBZhSBM" },
  { artist: "Phil Collins", name: "Strangers Like Me", youtubeId: "G02h2DJ3GCs" },
  { artist: "Haddaway", name: "What Is Love (7\" Mix)", youtubeId: "bizWqF8BmM0" },
  { artist: "Galantis", name: "Peanut Butter Jelly", youtubeId: "nAXP8wb7VWI" },
  { artist: "Mega Man X", name: "Storm Eagle (Sega Genesis Remix)", youtubeId: "F28uArEvtxI" },
  { artist: "Foreigner", name: "Head Games (2008 Remaster)", youtubeId: "CbHe-R3J7q8" },
  { artist: "Night Ranger", name: "Sister Christian", youtubeId: "D7S2qCKb6XE" },
  { artist: "Fatboy Slim", name: "Weapon Of Choice", youtubeId: "TsRvbnQVI6I" },
  { artist: "The Clash", name: "Should I Stay or Should I Go", youtubeId: "wjZMcWaniA4" },
  { artist: "Roxette", name: "Listen To Your Heart", youtubeId: "Hs4QTkx4a9Y" },
  { artist: "The Black Keys", name: "Lonely Boy", youtubeId: "9DYPfItb2fk" },
  { artist: "Steve Miller Band", name: "Fly Like An Eagle", youtubeId: "WuXwSyahgW4" },
  { artist: "Annie Lennox", name: "Walking on Broken Glass", youtubeId: "nSN0YysStgY" },
  { artist: "The Rembrandts", name: "I'll Be There for You (Theme From \"Friends\")", youtubeId: "RIjTq_OdFvo" },
  { artist: "Red Hot Chili Peppers", name: "Dani California", youtubeId: "4FkfyssnHqU" },
  { artist: "The Police", name: "Every Little Thing She Does Is Magic", youtubeId: "5WEjz2YoH80" },
  { artist: "U2", name: "Vertigo", youtubeId: "8TXnjGtIhyc" },
  { artist: "Puddle Of Mudd", name: "Blurry", youtubeId: "ui-TR4U9WOs" },
  { artist: "Bowling For Soup", name: "1985", youtubeId: "H1Pb-cRbspA" },
  { artist: "The Immortals", name: "Techno Syndrome (Mortal Kombat)", youtubeId: "kWO2AuJT67w" },
  { artist: "Queen", name: "Don't Stop Me Now", youtubeId: "RrDKoXWKMmY" },
  { artist: "Styx", name: "Too Much Time On My Hands", youtubeId: "MlzFvOzl75Y" },
  { artist: "Darren Korb", name: "A Proper Story (Bastion)", youtubeId: "Z9y0iFVAbDg" },
  { artist: "Kaskade", name: "Move For me", youtubeId: "FwKSZrF6aXE" },
  { artist: "Grand Funk Railroad", name: "Some Kind Of Wonderful (Remastered)", youtubeId: "NiaVYUdfAow" },
  { artist: "Zombie Nation", name: "Kernkraft 400", youtubeId: "gE2Cs7Ks2Zg" },
  { artist: "Pink Floyd", name: "Learning To Fly", youtubeId: "vcFXq5-XFeE" },
  { artist: "38 Special", name: "Caught Up In You", youtubeId: "zg21Rkew874" },
  { artist: "Daft Punk", name: "One More Time", youtubeId: "fa5IWHDbftI" },
  { artist: "Daði Freyr", name: "Think About Things", youtubeId: "yrtksZu_O5E" },
  { artist: "Lady Gaga", name: "Applause", youtubeId: "4cNaX8kFsUI" },
  { artist: "C418", name: "Minecraft (Minecraft)", youtubeId: "XuZDeT8zI5c" },
  { artist: "Post Malone, Swae Lee", name: "Sunflower (Spider-Man: Into the Spider-Verse)", youtubeId: "r7Rn4ryE_w8" },
  { artist: "Bruce Springsteen", name: "Born in the U.S.A.", youtubeId: "tRx212PUa4g" },
  { artist: "Smash Mouth", name: "Walkin' on the Sun", youtubeId: "p8LZhGUu7C8" },
  { artist: "Thin Lizzy", name: "The Boys Are Back In Town", youtubeId: "nN120kCiVyQ" },
  { artist: "Paul Simon", name: "You Can Call Me Al", youtubeId: "OMbfT3Wppjo" },
  { artist: "Electric Light Orchestra", name: "Don't Bring Me Down", youtubeId: "kW0HZy8J0v0" },
  { artist: "Shania Twain", name: "Man! I Feel Like A Woman!", youtubeId: "YGJBMFS02oY" },
  { artist: "Michael Jackson", name: "Smooth Criminal (2012 Remaster)", youtubeId: "wkJTd_wKl0k" },
  { artist: "Prince & The Revolution", name: "Let's Go Crazy", youtubeId: "eCM2dEWGf-o" },
  { artist: "Van Halen", name: "Panama (2015 Remaster)", youtubeId: "YRFKU6QvBJY" },
  { artist: "_ensnare_", name: "There Is Always Love", youtubeId: "jD6QXl1_Fds" },
  { artist: "Enigma", name: "Return To Innocence (Radio Edit)", youtubeId: "7vUjpAz7Z5k" },
  { artist: "Greg Kihn Band", name: "The Breakup Song", youtubeId: "fmyidCAFMtg" },
  { artist: "Dido", name: "White Flag", youtubeId: "j-fWDrZSiZs" },
  { artist: "Niko", name: "Night of Fire (Extended mix)", youtubeId: "7BTWpImCDq4" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Devils... Monsters (Halo: Combat Evolved)", youtubeId: "56w4VLURmGI" },
  { artist: "Fiction Factory", name: "[Feels Like] Heaven", youtubeId: "mR56DXA_Cg0" },
  { artist: "Kevin Rudolf, Lil Wayne", name: "Let It Rock", youtubeId: "1lAdfEsf4p8" },
  { artist: "Carl Douglas", name: "Kung Fu Fighting", youtubeId: "it3E6vtExSE" },
  { artist: "Michael Jackson", name: "Don't Stop 'Til You Get Enough", youtubeId: "n3qQtSRmHxo" },
  { artist: "Jimmy Buffett", name: "Margaritaville", youtubeId: "5BuqBkR4384" },
  { artist: "Nena", name: "99 Luftballons", youtubeId: "AT_0zXw2rRo" },
  { artist: "Rupert Holmes", name: "Escape (The Pina Colada Song)", youtubeId: "FXG_I_tf_i4" },
  { artist: "Third Eye Blind", name: "Semi-Charmed Life", youtubeId: "gjdLAsnR_Ws" },
  { artist: "Kenny Loggins", name: "Playing with the Boys (From \"Top Gun\" Original Soundtrack)", youtubeId: "CWUqYzKCxvE" },
  { artist: "The Rolling Stones", name: "Start Me Up", youtubeId: "VRwn2DeXhLs" },
  { artist: "The Cascades", name: "Rhythm of the Rain", youtubeId: "AtEKXIQCwYw" },
  { artist: "Steve Miller Band", name: "Rock'n Me", youtubeId: "baWTjg1QqS8" },
  { artist: "Tears For Fears", name: "Mad World", youtubeId: "vlRAstW6cCQ" },
  { artist: "Katy Perry", name: "Last Friday Night (T.G.I.F.)", youtubeId: "6RMt2II3QXQ" },
  { artist: "Genesis", name: "Land of Confusion", youtubeId: "CKrsAje9lxg" },
  { artist: "Alice Cooper", name: "Poison", youtubeId: "9K2ktd6Ajkc" },
  { artist: "C418", name: "Subwoofer Lullaby (Minecraft)", youtubeId: "ibUOxEBxVsE" },
  { artist: "Madonna", name: "Material Girl", youtubeId: "UZton86SuOg" },
  { artist: "The Black Keys", name: "Howlin' for You", youtubeId: "Zs3cyuXSFII" },
  { artist: "Madonna", name: "Holiday", youtubeId: "2Ngkn7zCObI" },
  { artist: "Heart", name: "Barracuda", youtubeId: "p6v6wWmEYvY" },
  { artist: "Nile Rodgers, Nataraj", name: "Never Surrender (Halo 2)", youtubeId: "EWEi_nSmohk" },
  { artist: "Journey", name: "Lights", youtubeId: "BPazVAtD-xQ" },
  { artist: "Creedence Clearwater Revival", name: "Bad Moon Rising", youtubeId: "SuRCxakQt-c" },
  { artist: "Jars Of Clay", name: "Flood", youtubeId: "Dhrzoq3WbV4" },
  { artist: "Bryan Adams", name: "Run To You", youtubeId: "nCBASt507WA" },
  { artist: "Talking Heads", name: "Once in a Lifetime (2005 Remaster)", youtubeId: "CHatn3_UxEU" },
  { artist: "Kenny Loggins", name: "Danger Zone (From \"Top Gun\" Original Soundtrack)", youtubeId: "9ID4RAqCqnQ" },
  { artist: "Green Day", name: "Wake Me up When September Ends", youtubeId: "ulRXvH8VOl8" },
  { artist: "Jerry Martin", name: "Rush Hour (SimCity 4)", youtubeId: "LRM61x0UU8E" },
  { artist: "Kool & The Gang", name: "Get Down On It", youtubeId: "1AVxBedMP4I" },
  { artist: "Journey", name: "Faithfully", youtubeId: "YalgKfrOdsI" },
  { artist: "Kiss", name: "Detroit Rock City (Edit)", youtubeId: "jUIAf-2Hre4" },
  { artist: "Toto", name: "Africa", youtubeId: "QAo_Ycocl1E" },
  { artist: "Otis Redding", name: "[Sittin' On] the Dock of the Bay", youtubeId: "Zu5chXCp1Ag" },
  { artist: "Aerosmith", name: "Dude Looks Like A Lady (Lyrics)", youtubeId: "acQ6jLe3R8E" },
  { artist: "Tom Petty", name: "Free Fallin'", youtubeId: "ikum949djQM" },
  { artist: "Beastie Boys", name: "Brass Monkey", youtubeId: "acY2VSskD80" },
  { artist: "Fleetwood Mac", name: "You Make Loving Fun (2004 Remaster)", youtubeId: "RqjXn2NflqU" },
  { artist: "The Police", name: "Message In A Bottle", youtubeId: "WMl1xKJeuuQ" },
  { artist: "Genesis", name: "Abacab (2007 Remaster)", youtubeId: "rCsPjYcTQ_M" },
  { artist: "Bo Burnham", name: "Bezos I", youtubeId: "7_EeCkHs-e0" },
  { artist: "Pink Guy", name: "Stfu", youtubeId: "GhJ043zp8hI" },
  { artist: "Grand Funk Railroad", name: "We're An American Band", youtubeId: "QxNXFNCTr2I" },
  { artist: "Laura Branigan", name: "Gloria", youtubeId: "fxf2y8Tl9Ts" },
  { artist: "David Bowie", name: "Let's Dance (2018 Remaster)", youtubeId: "gHlwJvPv9C0" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "A Walk in the Woods (Halo: Combat Evolved)", youtubeId: "y6DdRv6NIyY" },
  { artist: "Beastie Boys", name: "Sabotage", youtubeId: "B8CD2Rco8cQ" },
  { artist: "Kid Rock", name: "All Summer Long", youtubeId: "FiLwPQKxOCM" },
  { artist: "Barbra Streisand", name: "Memory", youtubeId: "z1qartep_3I" },
  { artist: "American Hi-Fi", name: "Flavor Of The Weak", youtubeId: "B-mi4SdTomM" },
  { artist: "Above & Beyond", name: "Giving It Out (feat. Zoë Johnston)", youtubeId: "5hJE3JCexDM" },
  { artist: "Tom Petty And The Heartbreakers", name: "Listen To Her Heart", youtubeId: "Amow_25-5Wc" },
  { artist: "The Killers", name: "Mr. Brightside", youtubeId: "m2zUrruKjDQ" },
  { artist: "Scorpions", name: "No One Like You", youtubeId: "Yp5UHsnWolY" },
  { artist: "Pink Floyd", name: "Money", youtubeId: "rwPM01cbQBc" },
  { artist: "The Killers", name: "Somebody Told Me", youtubeId: "liRMxUT8A2c" },
  { artist: "Little Big", name: "Go Bananas", youtubeId: "7ynh6LM-Mkc" },
  { artist: "Nickelback", name: "How You Remind Me", youtubeId: "vkvrbbtnp6s" },
  { artist: "Michael Sembello", name: "Maniac", youtubeId: "6GCNUeTFSbA" },
  { artist: "Stevie Nicks", name: "Edge of Seventeen (2016 Remaster)", youtubeId: "b5bgQjTmm3g" },
  { artist: "Rob Dougan", name: "Clubbed to Death (Kurayamino Variation)", youtubeId: "OwGuSPXPyX4" },
  { artist: "Def Leppard", name: "Armageddon It", youtubeId: "GgUnqQbNzoE" },
  { artist: "Fitz and The Tantrums", name: "The Walker", youtubeId: "A_300cnCdYI" },
  { artist: "Mötley Crüe", name: "Girls, Girls, Girls", youtubeId: "XZU5XyqnuyM" },
  { artist: "Cheap Trick", name: "I Want You to Want Me", youtubeId: "Er9HDEq3YIY" },
  { artist: "Bob Seger & The Silver Bullet Band", name: "Night Moves", youtubeId: "ePCiVK5Jjos" },
  { artist: "Yolanda Be Cool, DCup", name: "We No Speak Americano (Original Mix)", youtubeId: "lygg5Ju0nNU" },
  { artist: "Guster", name: "Satellite", youtubeId: "2CL4yXVmVBE" },
  { artist: "Shania Twain", name: "That Don't Impress Me Much", youtubeId: "lfAVsNSl9-g" },
  { artist: "Pink Floyd", name: "Another Brick In The Wall (Part 2)", youtubeId: "zz8frWcmthA" },
  { artist: "Boston", name: "Feelin' Satisfied", youtubeId: "5Gh-gQY1dus" },
  { artist: "Prince, Prince and The Revolution", name: "Raspberry Beret", youtubeId: "owJ8QR_qWRw" },
  { artist: "Green Day", name: "Boulevard of Broken Dreams", youtubeId: "gYCTXzOTnXg" },
  { artist: "Jet", name: "Are You Gonna Be My Girl", youtubeId: "54dLepp2b0A" },
  { artist: "Bill Wurtz", name: "Outside", youtubeId: "p0omtdahVJE" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Flawed Legacy (Halo 2)", youtubeId: "sVgkqB8Zdl0" },
  { artist: "Genesis", name: "Jesus He Knows Me (2007 Remaster)", youtubeId: "_gbMnDK1nCw" },
  { artist: "Kendrick Lamar", name: "DNA", youtubeId: "uX6uBHPGfSs" },
  { artist: "Boston", name: "Don't Look Back", youtubeId: "KvmNRXdb2ng" },
  { artist: "Santana, Chad Kroeger", name: "Into the Night", youtubeId: "-AwPbtYFe_8" },
  { artist: "Thompson Twins", name: "Hold Me Now", youtubeId: "3c3P86kALbk" },
  { artist: "Asia", name: "Heat Of The Moment", youtubeId: "nvdYll1euGU" },
  { artist: "The Allman Brothers Band", name: "Jessica", youtubeId: "vTOozRAJ8dU" },
  { artist: "Def Leppard", name: "Rock Of Ages", youtubeId: "fTAOLmEba4I" },
  { artist: "Bob Seger & The Silver Bullet Band", name: "Hollywood Nights", youtubeId: "l85SmjhBQz0" },
  { artist: "Pat Benatar", name: "We Belong", youtubeId: "CV6n5QBnne8" },
  { artist: "Prince", name: "When Doves Cry", youtubeId: "oTUSeac7IuQ" },
  { artist: "C418", name: "Stal (Minecraft)", youtubeId: "PRUtpWzsSEg" },
  { artist: "Boney M.", name: "Rasputin (Club Mix)", youtubeId: "6qMWRf0dU5s" },
  { artist: "Daughtry", name: "No Surprise", youtubeId: "ZBYJDzRyQxE" },
  { artist: "KC & The Sunshine Band", name: "Get Down Tonight (2004 Remaster)", youtubeId: "tUMk0RbZDZY" },
  { artist: "Eminem, Nate Dogg", name: "Till I Collapse", youtubeId: "CO4kW70AchE" },
  { artist: "20syl", name: "Ongoing Thing (feat. Oddisee)", youtubeId: "zKoOIsVGPpo" },
  { artist: "Sheryl Crow", name: "All I Wanna Do", youtubeId: "RiOtjXUpflY" },
  { artist: "Katrina & The Waves", name: "Walking On Sunshine", youtubeId: "HmR2IZjuMVc" },
  { artist: "070 Shake", name: "Guilty Conscience", youtubeId: "X0t8zeEiqEY" },
  { artist: "Manfred Mann's Earth Band, Manfred Mann's Earth Band", name: "Blinded By The Light", youtubeId: "JZW9meY2IPw" },
  { artist: "Gob", name: "Oh! Ellin", youtubeId: "K59ZIVrExA0" },
  { artist: "Goo Goo Dolls", name: "Name", youtubeId: "sQxszQ9BsxM" },
  { artist: "Pat Benatar", name: "Hit Me With Your Best Shot", youtubeId: "rXs9MXrHxVE" },
  { artist: "Katy Perry", name: "The One That Got Away", youtubeId: "64wxAbbWNag" },
  { artist: "Gorillaz", name: "DARE", youtubeId: "SZP0NFRKBbs" },
  { artist: "Matchbox Twenty", name: "If You're Gone", youtubeId: "2mCkuycJjJs" },
  { artist: "Kenny Loggins", name: "I'm Alright (Theme from \"Caddyshack\")", youtubeId: "e2eRRkw62y0" },
  { artist: "M|A|R|R|S", name: "Pump Up The Volume", youtubeId: "w9gOQgfPW4Y" },
  { artist: "The B-52's", name: "Love Shack", youtubeId: "LXZFtJceQC4" },
  { artist: "Bon Jovi", name: "Have A Nice Day", youtubeId: "_GorjQ1K8-U" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Luck (Halo 3)", youtubeId: "UbMxGrTVovg" },
  { artist: "Lou Bega", name: "Mambo No. 5 (a Little Bit of...)", youtubeId: "RUBvqz3ozv8" },
  { artist: "FM Attack", name: "A Million Miles Away", youtubeId: "pdZsv8CNl1w" },
  { artist: "Tove Lo", name: "Talking Body", youtubeId: "HfZ6rflYapM" },
  { artist: "Dschinghis Khan", name: "Moskau", youtubeId: "XM7vBXJAK-8" },
  { artist: "Guns N' Roses", name: "Sweet Child O' Mine", youtubeId: "oMfMUfgjiLg" },
  { artist: "Boston", name: "Cool The Engines", youtubeId: "jw0YNvlFOrI" },
  { artist: "Robin Schulz", name: "Sugar (feat. Francesco Yates)", youtubeId: "bvC_0foemLY" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Black Tower (Halo 3)", youtubeId: "q_UZnGb7Cj8" },
  { artist: "Jay Sean, Sean Paul, Lil Jon", name: "Do You Remember", youtubeId: "9LvgomJNXkg" },
  { artist: "The Animals", name: "Don't Let Me Be Misunderstood", youtubeId: "YMDrTMnm1IE" },
  { artist: "Ricky Martin", name: "Livin' la Vida Loca", youtubeId: "98B9ZHOlk2E" },
  { artist: "twenty one pilots", name: "Levitate", youtubeId: "YHoGXDYGkIw" },
  { artist: "Linkin Park", name: "Breaking the Habit", youtubeId: "_e7bqZGPyFI" },
  { artist: "Alexandra Stan", name: "Mr. Saxobeat", youtubeId: "yFoElsPalQM" },
  { artist: "Lee Greenwood", name: "God Bless The U.S.A.", youtubeId: "zR0lxM-IyUs" },
  { artist: "John Mellencamp", name: "Small Town", youtubeId: "rXJHLlQxZqI" },
  { artist: "Madonna", name: "Vogue", youtubeId: "ydFYm-oomec" },
  { artist: "Bee Gees", name: "Night Fever (Serban Mix)", youtubeId: "6bpd7Gkg0MQ" },
  { artist: "Daryl Hall & John Oates", name: "Private Eyes", youtubeId: "0aQKmbtp6Pc" },
  { artist: "Prince", name: "1999 (2019 Remaster)", youtubeId: "UWC4X_rTRsA" },
  { artist: "Red Hot Chili Peppers", name: "Californication", youtubeId: "A__cH65WRvE" },
  { artist: "VERKA SERDUCHKA, Андрей Данилко, DR", name: "Dancing Lasha Tumbai", youtubeId: "IBc7c5sWRbQ" },
  { artist: "Scorpions", name: "Rock You Like A Hurricane", youtubeId: "bNawbNsx52A" },
  { artist: "Dire Straits", name: "Money for Nothing", youtubeId: "T82VtnfKGd8" },
  { artist: "Falco", name: "Rock Me Amadeus", youtubeId: "OKxBk4V79Co" },
  { artist: "Tears For Fears", name: "Everybody Wants To Rule The World", youtubeId: "Qs-8xYwYJAQ" },
  { artist: "The Black Keys", name: "Little Black Submarines", youtubeId: "DhKAh4RJM0Q" },
  { artist: "Bruce Springsteen", name: "Dancing In the Dark", youtubeId: "nCFTL4IO6t4" },
  { artist: "Alice Cooper", name: "School's Out", youtubeId: "37ALmuMSHEI" },
  { artist: "Lady Gaga, Space Cowboy, Flo Rida", name: "Starstruck", youtubeId: "n6LBhLPCbc4" },
  { artist: "Guns N' Roses", name: "Live And Let Die", youtubeId: "RywqQ_AKB9M" },
  { artist: "38 Special", name: "Hold On Loosely", youtubeId: "g3nn6WfFQ7o" },
  { artist: "M.O.O.N.", name: "'Paris' [Hotline Miami Soundtrack]", youtubeId: "8wXRvvGr8Ug" },
  { artist: "Linkin Park", name: "In the End", youtubeId: "Un8Uv1psMOI" },
  { artist: "Bill Wurtz", name: "La de Da de Da de Da de Day Oh", youtubeId: "atVsmnCX1-Q" },
  { artist: "Bon Jovi", name: "Livin' On A Prayer", youtubeId: "YBdyc1WDlBQ" },
  { artist: "Mötley Crüe", name: "Wild Side", youtubeId: "MVkTYD_3XPA" },
  { artist: "Dave Rodgers", name: "Beat of the Rising Sun", youtubeId: "5WyN2y2FPnQ" },
  { artist: "Smash Mouth", name: "All Star", youtubeId: "-_RBJvfoszk" },
  { artist: "Fitz and The Tantrums", name: "HandClap", youtubeId: "5AtkWnBjGBU" },
  { artist: "3 Doors Down", name: "Be Like That", youtubeId: "HHpMtWtgUvc" },
  { artist: "Eric Clapton", name: "Cocaine", youtubeId: "8QYdIswhbY4" },
  { artist: "Judy Collins", name: "Both Sides Now", youtubeId: "MYKi_Cj4s5s" },
  { artist: "The Traveling Wilburys", name: "Heading For The Light", youtubeId: "SI-il17vJ3w" },
  { artist: "Joan Jett", name: "Bad Reputation", youtubeId: "x6fB8KMUnz0" },
  { artist: "Pitbull, Christina Aguilera", name: "Feel This Moment", youtubeId: "r90Wwl2MPq0" },
  { artist: "Righeira", name: "No Tengo Dinero (1983 Maxi)", youtubeId: "2fXWJX3tTXI" },
  { artist: "Amy Grant", name: "Baby, Baby", youtubeId: "PnAD2Tb-SE8" },
  { artist: "Billy Joel", name: "We Didn't Start the Fire", youtubeId: "55q6jrfBDdk" },
  { artist: "Coldplay", name: "Speed of Sound", youtubeId: "04tC72kZM_o" },
  { artist: "James Brown", name: "Get Up Offa That Thing", youtubeId: "2ATmDmLAMWw" },
  { artist: "Bryan Adams", name: "Cuts Like A Knife (Classic Version)", youtubeId: "4J_QbsH-Onk" },
  { artist: "Blue Oyster Cult", name: "(Don't Fear) The Reaper", youtubeId: "Dy4HA3vUv2c" },
  { artist: "Elton John", name: "Rocket Man (I Think It's Going To Be A Long, Long Time)", youtubeId: "BdEe5SpdIuo" },
  { artist: "Huey Lewis & The News", name: "I Want A New Drug", youtubeId: "0PhqlB-uTX8" },
  { artist: "OK Go", name: "Do What You Want", youtubeId: "zUTQ6b8Uq6g" },
  { artist: "The Human League", name: "Don't You Want Me", youtubeId: "UscEO2ITyug" },
  { artist: "Flo Rida, T-Pain", name: "Low (feat. T-Pain)", youtubeId: "uUL8a7eJCk8" },
  { artist: "Nickelback", name: "Rockstar", youtubeId: "OiQEfJFMzDw" },
  { artist: "The Killers", name: "When You Were Young", youtubeId: "s2gtQJiM5Zg" },
  { artist: "Daughtry, Slash", name: "What I Want", youtubeId: "7ems67L-zNY" },
  { artist: "Jordin Sparks", name: "S.O.S. (Let the Music Play)", youtubeId: "ecme6iALZzE" },
  { artist: "Joji", name: "Run", youtubeId: "7qo7ESpyDNY" },
  { artist: "Journey", name: "Don't Stop Believin'", youtubeId: "kMgaA6RkcVU" },
  { artist: "The Black Crowes", name: "Hard To Handle", youtubeId: "h1WItDnFtTk" },
  { artist: "Metallica", name: "Enter Sandman", youtubeId: "Np0zgpkxAaA" },
  { artist: "Goo Goo Dolls", name: "Black Balloon", youtubeId: "dH7pJy-VcTA" },
  { artist: "Naked Eyes", name: "Always Something There to Remind Me (2018 Remaster)", youtubeId: "e2fQxbEshtA" },
  { artist: "Jimmy Eat World", name: "The Middle", youtubeId: "rubpIfLPzvU" },
  { artist: "Elton John", name: "Bennie And The Jets", youtubeId: "ZBUW433Porw" },
  { artist: "Imagine Dragons", name: "Radioactive", youtubeId: "3Yb2-CWjrME" },
  { artist: "Of Monsters and Men", name: "Mountain Sound", youtubeId: "6TmJF5jMcus" },
  { artist: "Huey Lewis & The News", name: "The Heart Of Rock & Roll (Single Edit)", youtubeId: "z8rZ_iS2vX8" },
  { artist: "Scorpions", name: "No One Like You", youtubeId: "qKhorc1aYro" },
  { artist: "blink-182", name: "First Date", youtubeId: "-3mTma5zL2Y" },
  { artist: "Journey", name: "Separate Ways (Worlds Apart)", youtubeId: "haCOU64qCo4" },
  { artist: "Bowling For Soup", name: "Punk Rock 101", youtubeId: "UQQRJ8UfExU" },
  { artist: "Raspberries", name: "Go All The Way", youtubeId: "rtp8WSAzrGw" },
  { artist: "Electric Light Orchestra", name: "Last Train to London", youtubeId: "u8axoBf5QWo" },
  { artist: "Selena Gomez & The Scene", name: "Naturally", youtubeId: "50gktcuxdAA" },
  { artist: "Florence + The Machine", name: "You've Got The Love", youtubeId: "92NvPOFaKpA" },
  { artist: "TLC", name: "No Scrubs", youtubeId: "q3MkrF5fPew" },
  { artist: "Pop Up!", name: "Paradise City", youtubeId: "xATTkS5Lwb0" },
  { artist: "\"Weird Al\" Yankovic", name: "Hardware Store", youtubeId: "DFI6cV9slfI" },
  { artist: "Scandal, Patty Smyth", name: "The Warrior", youtubeId: "hN9-PjWVD8A" },
  { artist: "Screaming Jay Hawkins", name: "Little Demon", youtubeId: "hpC-LAbkXTM" },
  { artist: "Commodores", name: "Brick House", youtubeId: "gn6b9coJz3s" },
  { artist: "Fleetwood Mac", name: "Everywhere", youtubeId: "wLSUDSNqLgQ" },
  { artist: "Young MC", name: "Bust A Move", youtubeId: "6rM8ksGHnFc" },
  { artist: "Tom Petty And The Heartbreakers", name: "Mary Jane's Last Dance", youtubeId: "M8XaGxvuFOU" },
  { artist: "BattleBlock Theater Music", name: "Secret Area", youtubeId: "zwZISypgA9M" },
  { artist: "Steve Winwood", name: "Higher Love", youtubeId: "PagMEUbbBcs" },
  { artist: "Enrique Iglesias, Descemer Bueno, Gente De Zona", name: "Bailando (Spanish Version)", youtubeId: "Iz0hjRq40ko" },
  { artist: "Joan Jett & the Blackhearts", name: "I Hate Myself for Loving You", youtubeId: "V6m7b5xJq7Y" },
  { artist: "KT Tunstall", name: "Suddenly I See", youtubeId: "eX7lFYAaO-c" },
  { artist: "Enrique Iglesias, Pitbull", name: "I Like It", youtubeId: "FAqhvV1k45E" },
  { artist: "Jim Guthrie", name: "Dark Flute", youtubeId: "6L5lJ-WRYaA" },
  { artist: "Theory Of A Deadman", name: "Rx (Medicate)", youtubeId: "cpBpTio4JBs" },
  { artist: "The National", name: "Exile, Vilify (Portal 2)", youtubeId: "XUwkGFw226U" },
  { artist: "Shinedown", name: "Second Chance", youtubeId: "kOFVsn6U9L8" },
  { artist: "Berlin", name: "Take My Breath Away (Love Theme from \"Top Gun\")", youtubeId: "F4M6haOFtcE" },
  { artist: "The Cars", name: "Magic", youtubeId: "qB_2B5tVbtk" },
  { artist: "Jaytech", name: "Pepe's Garden (Original Mix)", youtubeId: "l8nt2eCvsrg" },
  { artist: "Aretha Franklin", name: "Respect", youtubeId: "A134hShx_gw" },
  { artist: "Foreigner", name: "Double Vision (2008 Remaster)", youtubeId: "j9K68tR9IsE" },
  { artist: "The Gap Band", name: "You Dropped A Bomb On Me", youtubeId: "hbh3XBwo9k4" },
  { artist: "Martin O’Donnell, Michael Salvatori", name: "Three Gates (Halo 3)", youtubeId: "d0zr33BwWMg" },
  { artist: "Nitro Fun, Hyper Potions", name: "Checkpoint (Sonic Mania)", youtubeId: "0G2ZAq1CZVg" },
  { artist: "ABBA", name: "Dancing Queen", youtubeId: "YkLLcIKhJ64" },
  { artist: "Lady Gaga, Beyoncé", name: "Telephone", youtubeId: "KfSVnUvKyZ0" },
  { artist: "AC/DC", name: "T.N.T.", youtubeId: "NhsK5WExrnE" },
  { artist: "Rob Thomas", name: "This Is How a Heart Breaks", youtubeId: "th9FF3Gefvs" },
  { artist: "Def Leppard", name: "Photograph", youtubeId: "hkG0P6OuTVM" },
  { artist: "The Allman Brothers Band", name: "Midnight Rider", youtubeId: "Z8zk7XKyoE8" },
  { artist: "Talk Talk", name: "It's My Life", youtubeId: "yWQezjGjiqs" },
  { artist: "Jon Bellion, Travis Mendes", name: "Guillotine", youtubeId: "58p4OTAP91c" },
  { artist: "Eric Carmen", name: "All by Myself", youtubeId: "iN9CjAfo5n0" },
  { artist: "Michael Jackson", name: "Bad (2012 Remaster)", youtubeId: "-DlMoJ2V6uk" },
  { artist: "Shaggy, Ricardo Ducent", name: "It Wasn't Me", youtubeId: "sTMgX1PDGAE" },
  { artist: "Blondie", name: "Call Me", youtubeId: "tykf2xYPNdc" },
  { artist: "M83", name: "Midnight City", youtubeId: "7ID-1jzek4Y" },
  { artist: "Pitbull, Ne-Yo, Afrojack, Nayer", name: "Give Me Everything", youtubeId: "E2lX1ZovtcA" },
  { artist: "Fleetwood Mac", name: "Rhiannon", youtubeId: "0xGPi-Al3zQ" },
  { artist: "Cher", name: "Believe", youtubeId: "oOGxKLUMbbc" },
  { artist: "John Mellencamp", name: "Pink Houses", youtubeId: "2uCQzHtGt6Q" },
  { artist: "The Who", name: "Baba O'Riley", youtubeId: "rIbMbXjbW98" },
  { artist: "The Heavy", name: "Short Change Hero", youtubeId: "GjTTB6yII4o" },
  { artist: "O-Zone", name: "Dragostea din tei", youtubeId: "f7P5Q2IIT4U" },
  { artist: "Jonathan Coulton", name: "Want You Gone (Portal 2)", youtubeId: "dVVZaZ8yO6o" },
  { artist: "Goo Goo Dolls", name: "Iris", youtubeId: "Dy_eP-mqWow" },
  { artist: "Seal", name: "Kiss from a Rose", youtubeId: "49ubX7n1BaQ" },
  { artist: "The Romantics", name: "Talking in Your Sleep", youtubeId: "YpZgagU50KE" },
  { artist: "Van Halen", name: "Dance the Night Away (2015 Remaster)", youtubeId: "E-rTKd-Alk8" },
  { artist: "4 Non Blondes", name: "What's Up", youtubeId: "6NXnxTNIWkc" },
  { artist: "Madonna", name: "Into the Groove (Edit)", youtubeId: "1zh-0eupfNw" },
  { artist: "Sound Remedy & Nitro Fun", name: "Turbo Penguin", youtubeId: "IQOlBJXSB2s" },
  { artist: "Five for Fighting", name: "100 Years", youtubeId: "pA-YIAYKB4I" },
  { artist: "AC/DC", name: "Thunderstruck", youtubeId: "v2AC41dglnM" },
  { artist: "Lady Gaga, Colby O'Donis", name: "Just Dance", youtubeId: "ACNwMzZejQQ" },
  { artist: "The Vapors", name: "Turning Japanese", youtubeId: "nhD9gyRSz0g" },
  { artist: "10cc", name: "Honeymoon With B Troop", youtubeId: "xTlgQCrd7bk" },
  { artist: "Saki Kabata", name: "Lonely Rolling Star (Katamari Damacy)", youtubeId: "7_QydNXI_ok" },
  { artist: "Styx", name: "Renegade", youtubeId: "E9eLz4DrwF8" },
  { artist: "Earth, Wind & Fire", name: "September", youtubeId: "3cKtSlsYVEU" },
  { artist: "Jason Mraz", name: "The Remedy (I Won't Worry)", youtubeId: "R7EYYL4Q0Ao" },
  { artist: "Duran Duran", name: "Ordinary World", youtubeId: "vm5iK_tNWAg" },
  { artist: "Badfinger", name: "Baby Blue", youtubeId: "33oAuvbRg-c" },
  { artist: "The Script", name: "For the First Time", youtubeId: "u1lD5gDw6Lo" },
  { artist: "twenty one pilots", name: "Stressed Out", youtubeId: "K1FlAphL2p8" },
  { artist: "Hilary Duff", name: "Come Clean", youtubeId: "bChbkVRX3jM" },
  { artist: "Toby Fox", name: "Death by Glamour (Undertale)", youtubeId: "2TgO-tN5wAM" },
  { artist: "Maxine Nightingale", name: "Right Back Where We Started From", youtubeId: "JoI7MLxGRjQ" },
];
